"""Vendor sell prices for every item -> salusnovus/Data/VendorPrices.lua

    python build_vendor_prices.py

From this client's own item table (db2/<build>/ItemSparse.csv, with the
hotfix rows in ItemSparse_hotfix.csv overriding). The auction sniper needs
the vendor price of thousands of items at once; asking the client item by
item means waiting on its cache, so it ships here instead.
Only items a vendor pays for (SellPrice > 0) and that can be traded
(not bind-on-pickup) are written.
"""
import csv
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD = "1.60.1.69913"
OUT = os.path.join(HERE, "salusnovus", "Data", "VendorPrices.lua")
BIND_ON_PICKUP = {1, 4}       # 1 = on pickup, 4 = quest item
# Forever's server overrides some vendor prices the client table still has
# old: every wand sells for 1 copper (Alex, 2026-10-05). (ClassID, SubclassID)
OVERRIDES = {(2, 19): 1}


def read(path):
    rows = {}
    if not os.path.exists(path):
        return rows
    with io.open(path, encoding="utf-8", newline="") as fh:
        for r in csv.DictReader(fh):
            try:
                rows[int(r["ID"])] = r
            except (KeyError, ValueError):
                continue
    return rows


def prices(build=BUILD):
    base = os.path.join(HERE, "db2", build)
    rows = read(os.path.join(base, "ItemSparse.csv"))
    rows.update(read(os.path.join(base, "ItemSparse_hotfix.csv")))
    kinds = read(os.path.join(base, "Item.csv"))
    out = {}
    for item_id, r in rows.items():
        try:
            sell = int(r.get("SellPrice") or 0)
            bond = int(r.get("Bonding") or 0)
        except ValueError:
            continue
        k = kinds.get(item_id) or {}
        try:
            kind = (int(k.get("ClassID") or -1), int(k.get("SubclassID") or -1))
        except ValueError:
            kind = (-1, -1)
        if kind in OVERRIDES:
            sell = OVERRIDES[kind]
        if sell > 0 and bond not in BIND_ON_PICKUP:
            out[item_id] = sell
    return out


def lua(table):
    lines = ["-- GENERATED by build_vendor_prices.py from the client's ItemSparse table. Do not edit.",
             "-- itemID -> what a vendor pays for one, in copper.",
             "local _, ns = ...",
             "ns.VendorSell = {"]
    row = []
    for item_id in sorted(table):
        row.append("[%d]=%d" % (item_id, table[item_id]))
        if len(row) == 10:
            lines.append("    " + ",".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ",".join(row) + ",")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    table = prices()
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(lua(table))
    print("wrote %d vendor prices -> %s" % (len(table), os.path.relpath(OUT, HERE)))


if __name__ == "__main__":
    sys.exit(main())
