-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[531] = {
    name = "Ahn'Qiraj Temple",
    mapID = 531,
    type = "raid",
    level = nil,
    pulls = 0,
    bosses = {
        {
            encounterID = 709, encounterIDs = { 709 },
            name = "The Prophet Skeram",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15263, name = "The Prophet Skeram", displayID = 15345 },
            },
            abilities = {
            },
        },
        {
            encounterID = 710, encounterIDs = { 710 },
            name = "Silithid Royalty",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 711, encounterIDs = { 711 },
            name = "Battleguard Sartura",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15516, name = "Battleguard Sartura", displayID = 15583 },
            },
            abilities = {
            },
        },
        {
            encounterID = 712, encounterIDs = { 712 },
            name = "Fankriss the Unyielding",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15510, name = "Fankriss the Unyielding", displayID = 125331 },
            },
            abilities = {
            },
        },
        {
            encounterID = 713, encounterIDs = { 713 },
            name = "Viscidus",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15299, name = "Viscidus", displayID = 15686 },
            },
            abilities = {
            },
        },
        {
            encounterID = 714, encounterIDs = { 714 },
            name = "Princess Huhuran",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15509, name = "Princess Huhuran", displayID = 15739 },
            },
            abilities = {
            },
        },
        {
            encounterID = 715, encounterIDs = { 715 },
            name = "Twin Emperors",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 716, encounterIDs = { 716 },
            name = "Ouro",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15517, name = "Ouro", displayID = 15509 },
            },
            abilities = {
            },
        },
        {
            encounterID = 717, encounterIDs = { 717 },
            name = "C'thun",
            order = 8000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15727, name = "C'thun", displayID = 15787 },
            },
            abilities = {
            },
        },
    },
}
