-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[900003] = {
    name = "Alcaz Prison",
    mapID = 900003,
    type = "dungeon",
    level = 48,
    levelMax = 53, levelRange = "48-53",
    coming = true,   -- on Blizzard's chart, not in the client tables yet
    pulls = 0,
    bosses = {
    },
}
