-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[229] = {
    name = "Blackrock Spire",
    mapID = 229,
    type = "dungeon",
    level = 57,
    levelMax = 60, levelRange = "57-60",
    pulls = 0,
    bosses = {
        {
            encounterID = 267, encounterIDs = { 267 },
            name = "Highlord Omokk",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9196, name = "Highlord Omokk", displayID = 11565 },
            },
            abilities = {
            },
        },
        {
            encounterID = 268, encounterIDs = { 268 },
            name = "Shadow Hunter Vosh'gajin",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9236, name = "Shadow Hunter Vosh'gajin", displayID = 9732 },
            },
            abilities = {
            },
        },
        {
            encounterID = 269, encounterIDs = { 269 },
            name = "War Master Voone",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9237, name = "War Master Voone", displayID = 9733 },
            },
            abilities = {
            },
        },
        {
            encounterID = 270, encounterIDs = { 270 },
            name = "Mother Smolderweb",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10596, name = "Mother Smolderweb", displayID = 9929 },
            },
            abilities = {
            },
        },
        {
            encounterID = 271, encounterIDs = { 271 },
            name = "Urok Doomhowl",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10584, name = "Urok Doomhowl", displayID = 11583 },
            },
            abilities = {
            },
        },
        {
            encounterID = 272, encounterIDs = { 272 },
            name = "Quartermaster Zigris",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9736, name = "Quartermaster Zigris", displayID = 9738 },
            },
            abilities = {
            },
        },
        {
            encounterID = 274, encounterIDs = { 274 },
            name = "Halycon",
            order = 5500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10220, name = "Halycon", displayID = 9567 },
            },
            abilities = {
            },
        },
        {
            encounterID = 273, encounterIDs = { 273 },
            name = "Gizrul the Slavener",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10268, name = "Gizrul the Slavener", displayID = 9564 },
            },
            abilities = {
            },
        },
        {
            encounterID = 275, encounterIDs = { 275 },
            name = "Overlord Wyrmthalak",
            order = 8000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9568, name = "Overlord Wyrmthalak", displayID = 8711 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3062, encounterIDs = { 3062 },
            name = "Pyroguard Emberseer",
            order = 9000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9816, name = "Pyroguard Emberseer", displayID = 2172 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3063, encounterIDs = { 3063 },
            name = "Warchief Rend Blackhand",
            order = 10000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10429, name = "Warchief Rend Blackhand", displayID = 9778 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3068, encounterIDs = { 3068 },
            name = "The Beast",
            order = 11000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10430, name = "The Beast", displayID = 10193 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3069, encounterIDs = { 3069 },
            name = "General Drakkisath",
            order = 12000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10363, name = "General Drakkisath", displayID = 10115 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3070, encounterIDs = { 3070 },
            name = "Lord Valthalak",
            order = 13000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 16042, name = "Lord Valthalak", displayID = 14308 },
            },
            abilities = {
            },
        },
    },
}
