-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[48] = {
    name = "Blackfathom Deeps",
    mapID = 48,
    type = "dungeon",
    level = 25,
    levelMax = 31, levelRange = "25-31",
    pulls = 0,
    bosses = {
        {
            encounterID = 2916, encounterIDs = { 2916, 2761, 2697 },
            name = "Ghamoo-ra",
            order = -6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 201722, name = "Ghamoo-ra", displayID = 111481 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2915, encounterIDs = { 2915, 2762, 2699 },
            name = "Lady Sarevess",
            order = -5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 204068, name = "Lady Sarevess", displayID = 112103 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2914, encounterIDs = { 2914, 2763, 2704 },
            name = "Gelihast",
            order = -4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 204921, name = "Gelihast", displayID = 5243 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2913, encounterIDs = { 2913, 2764, 2710 },
            name = "Lorgus Jett",
            order = -3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 207356, name = "Lorgus Jett", displayID = 12822 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2912, encounterIDs = { 2912, 2765 },
            name = "Old Serra'kis",
            order = -2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4830, name = "Old Serra'kis", displayID = 1816 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2911, encounterIDs = { 2911, 2766, 2825 },
            name = "Twilight Lord Kelris",
            order = -1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 209678, name = "Twilight Lord Kelris", displayID = 4939 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2694, encounterIDs = { 2694 },
            name = "Baron Aquanis",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 202699, name = "Baron Aquanis", displayID = 110 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2910, encounterIDs = { 2910, 2767, 2891 },
            name = "Aku'mai",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 213334, name = "Aku'mai", displayID = 116784 },
            },
            abilities = {
            },
        },
    },
}
