-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[900004] = {
    name = "Blackmaw Hold",
    mapID = 900004,
    type = "dungeon",
    level = 55,
    levelMax = 60, levelRange = "55-60",
    coming = true,   -- on Blizzard's chart, not in the client tables yet
    pulls = 0,
    bosses = {
    },
}
