-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[230] = {
    name = "Blackrock Depths",
    mapID = 230,
    type = "dungeon",
    level = 52,
    levelMax = 60, levelRange = "52-60",
    pulls = 0,
    bosses = {
        {
            encounterID = 227, encounterIDs = { 227 },
            name = "High Interrogator Gerstahn",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9018, name = "High Interrogator Gerstahn", displayID = 8761 },
            },
            abilities = {
            },
        },
        {
            encounterID = 228, encounterIDs = { 228 },
            name = "Lord Roccor",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9025, name = "Lord Roccor", displayID = 5781 },
            },
            abilities = {
            },
        },
        {
            encounterID = 229, encounterIDs = { 229 },
            name = "Houndmaster Grebmar",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9319, name = "Houndmaster Grebmar", displayID = 9212 },
            },
            abilities = {
            },
        },
        {
            encounterID = 230, encounterIDs = { 230 },
            name = "Ring of Law",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 231, encounterIDs = { 231 },
            name = "Pyromancer Loregrain",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9024, name = "Pyromancer Loregrain", displayID = 8762 },
            },
            abilities = {
            },
        },
        {
            encounterID = 232, encounterIDs = { 232 },
            name = "Lord Incendius",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9017, name = "Lord Incendius", displayID = 1204 },
            },
            abilities = {
            },
        },
        {
            encounterID = 233, encounterIDs = { 233 },
            name = "Warder Stilgiss",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9041, name = "Warder Stilgiss", displayID = 9089 },
            },
            abilities = {
            },
        },
        {
            encounterID = 234, encounterIDs = { 234 },
            name = "Fineous Darkvire",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9056, name = "Fineous Darkvire", displayID = 8704 },
            },
            abilities = {
            },
        },
        {
            encounterID = 235, encounterIDs = { 235 },
            name = "Bael'Gar",
            order = 8000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9016, name = "Bael'Gar", displayID = 12162 },
            },
            abilities = {
            },
        },
        {
            encounterID = 236, encounterIDs = { 236 },
            name = "General Angerforge",
            order = 9000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9033, name = "General Angerforge", displayID = 8756 },
            },
            abilities = {
            },
        },
        {
            encounterID = 237, encounterIDs = { 237 },
            name = "Golem Lord Argelmach",
            order = 10000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 8983, name = "Golem Lord Argelmach", displayID = 8759 },
            },
            abilities = {
            },
        },
        {
            encounterID = 238, encounterIDs = { 238 },
            name = "Hurley Blackbreath",
            order = 11000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9537, name = "Hurley Blackbreath", displayID = 8658 },
            },
            abilities = {
            },
        },
        {
            encounterID = 239, encounterIDs = { 239 },
            name = "Phalanx",
            order = 12000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9502, name = "Phalanx", displayID = 8177 },
            },
            abilities = {
            },
        },
        {
            encounterID = 240, encounterIDs = { 240 },
            name = "Ribbly Screwspigot",
            order = 13000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9543, name = "Ribbly Screwspigot", displayID = 8667 },
            },
            abilities = {
            },
        },
        {
            encounterID = 241, encounterIDs = { 241 },
            name = "Plugger Spazzring",
            order = 14000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9499, name = "Plugger Spazzring", displayID = 8652 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2791, encounterIDs = { 2791 },
            name = "The Vault",
            order = 14500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10120, name = "The Vault", displayID = 5989 },
            },
            abilities = {
            },
        },
        {
            encounterID = 242, encounterIDs = { 242 },
            name = "Ambassador Flamelash",
            order = 15000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9156, name = "Ambassador Flamelash", displayID = 8329 },
            },
            abilities = {
            },
        },
        {
            encounterID = 243, encounterIDs = { 243 },
            name = "The Seven",
            order = 16000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 244, encounterIDs = { 244 },
            name = "Magmus",
            order = 17000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9938, name = "Magmus", displayID = 12162 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2789, encounterIDs = { 2789 },
            name = "Princess Moira Bronzebeard",
            order = 18000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 8929, name = "Princess Moira Bronzebeard", displayID = 8705 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2790, encounterIDs = { 2790 },
            name = "Emperor Dagran Thaurissan",
            order = 19000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 9019, name = "Emperor Dagran Thaurissan", displayID = 8807 },
            },
            abilities = {
            },
        },
    },
}
