-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[469] = {
    name = "Blackwing Lair",
    mapID = 469,
    type = "raid",
    level = 60,
    pulls = 0,
    bosses = {
        {
            encounterID = 610, encounterIDs = { 610 },
            name = "Razorgore the Untamed",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12435, name = "Razorgore the Untamed", displayID = 10115 },
            },
            abilities = {
            },
        },
        {
            encounterID = 611, encounterIDs = { 611 },
            name = "Vaelastrasz the Corrupt",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 13020, name = "Vaelastrasz the Corrupt", displayID = 13992 },
            },
            abilities = {
            },
        },
        {
            encounterID = 612, encounterIDs = { 612 },
            name = "Broodlord Lashlayer",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12017, name = "Broodlord Lashlayer", displayID = 14308 },
            },
            abilities = {
            },
        },
        {
            encounterID = 613, encounterIDs = { 613 },
            name = "Firemaw",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11983, name = "Firemaw", displayID = 6377 },
            },
            abilities = {
            },
        },
        {
            encounterID = 614, encounterIDs = { 614 },
            name = "Ebonroc",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14601, name = "Ebonroc", displayID = 6377 },
            },
            abilities = {
            },
        },
        {
            encounterID = 615, encounterIDs = { 615 },
            name = "Flamegor",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11981, name = "Flamegor", displayID = 6377 },
            },
            abilities = {
            },
        },
        {
            encounterID = 616, encounterIDs = { 616 },
            name = "Chromaggus",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14020, name = "Chromaggus", displayID = 14367 },
            },
            abilities = {
            },
        },
        {
            encounterID = 617, encounterIDs = { 617 },
            name = "Nefarian",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11583, name = "Nefarian", displayID = 11380 },
            },
            abilities = {
            },
        },
    },
}
