-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[2959] = {
    name = "City of Dalaran",
    mapID = 2959,
    type = "dungeon",
    level = 28,
    levelMax = 33, levelRange = "28-33",
    pulls = 0,
    bosses = {
        {
            encounterID = 3298, encounterIDs = { 3298 },
            name = "Arcane Anomaly",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3299, encounterIDs = { 3299 },
            name = "Fel Ancient",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3300, encounterIDs = { 3300 },
            name = "Mana Devourer",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3301, encounterIDs = { 3301 },
            name = "Mana Elemental",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 240352, name = "Mana Elemental", displayID = 14253 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3302, encounterIDs = { 3302 },
            name = "Unstable Sentinel",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3303, encounterIDs = { 3303 },
            name = "Shade of the Archmage",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3310, encounterIDs = { 3310 },
            name = "Lyn the Ignored",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3311, encounterIDs = { 3311 },
            name = "Atrexis the Grave Knight",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3312, encounterIDs = { 3312 },
            name = "Mana Wraith",
            order = 8000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
    },
}
