-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[36] = {
    name = "Deadmines",
    mapID = 36,
    type = "dungeon",
    level = 18,
    levelMax = 24, levelRange = "18-24",
    pulls = 0,
    bosses = {
        {
            encounterID = 2741, encounterIDs = { 2741 },
            name = "Rhahk'Zor",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 644, name = "Rhahk'Zor", displayID = 14403 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2742, encounterIDs = { 2742 },
            name = "Sneed",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 643, name = "Sneed", displayID = 7125 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2743, encounterIDs = { 2743 },
            name = "Gilnid",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 1763, name = "Gilnid", displayID = 7124 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2744, encounterIDs = { 2744 },
            name = "Captain Greenskin",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 647, name = "Captain Greenskin", displayID = 7113 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2745, encounterIDs = { 2745 },
            name = "Mr. Smite",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 646, name = "Mr. Smite", displayID = 2026 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2746, encounterIDs = { 2746 },
            name = "Cookie",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 645, name = "Cookie", displayID = 1305 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2747, encounterIDs = { 2747 },
            name = "Edwin VanCleef",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 639, name = "Edwin VanCleef", displayID = 2029 },
            },
            abilities = {
            },
        },
    },
}
