-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json) + logs WoWCombatLog-092026_095152.txt. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[36] = {
    name = "Deadmines",
    mapID = 36,
    type = "dungeon",
    level = 18,
    levelMax = 24, levelRange = "18-24",
    pulls = 4,
    bosses = {
        {
            encounterID = 2741, encounterIDs = { 2741 },
            name = "Rhahk'Zor",
            order = 0,
            pulls = 1, kills = 1,
            avgLength = 48.3,
            npcs = {
                { id = 644, name = "Rhahk'Zor", displayID = 14403 },
            },
            abilities = {
                { spellID = 6304, name = "Rhahk'Zor Slam", source = "Rhahk'Zor", pulls = 1,
                  casts = { { 2.4, "success", 1 }, { 19.4, "success", 1 }, { 44.9, "success", 1 } },
                  lanes = { casts = { 2.4, 19.4, 44.9 }, spread = { 0.0, 0.0, 0.0 }, support = { 1, 1, 1 }, cast = 0.0 } },
            },
        },
        {
            encounterID = 2742, encounterIDs = { 2742 },
            name = "Sneed",
            order = 1000,
            pulls = 1, kills = 1,
            avgLength = 98.8,
            npcs = {
                { id = 643, name = "Sneed", displayID = 7125 },
                { id = 641, name = "Goblin Woodcarver", displayID = nil },
                { id = 642, name = "Sneed's Shredder", displayID = nil },
            },
            abilities = {
                { spellID = 5532, name = "Cleave", source = "Goblin Woodcarver", pulls = 1,
                  casts = { { 2.4, "success", 1 }, { 19.8, "success", 1 } },
                  lanes = { casts = { 2.4, 19.8 }, spread = { 0.0, 0.0 }, support = { 1, 1 }, cast = 0.0 } },
                { spellID = 3603, name = "Distracting Pain", source = "Sneed's Shredder", pulls = 1,
                  casts = { { 11.8, "success", 1 }, { 61.8, "success", 1 } },
                  lanes = { casts = { 11.8, 61.8 }, spread = { 0.0, 0.0 }, support = { 1, 1 }, cast = 0.0 } },
                { spellID = 7399, name = "Terrify", source = "Sneed's Shredder", pulls = 1,
                  casts = { { 13.0, "success", 1 }, { 54.9, "success", 1 } },
                  lanes = { casts = { 13.0, 54.9 }, spread = { 0.0, 0.0 }, support = { 1, 1 }, cast = 0.0 } },
                { spellID = 5141, name = "Eject Sneed", source = "Sneed's Shredder", pulls = 1,
                  casts = { { 66.3, "success", 1 } },
                  lanes = { casts = { 66.3 }, spread = { 0.0 }, support = { 1 }, cast = 0.0 } },
                { spellID = 6713, name = "Disarm", source = "Sneed", pulls = 1,
                  casts = { { 84.1, "success", 1 } },
                  lanes = { casts = { 84.1 }, spread = { 0.0 }, support = { 1 }, cast = 0.0 } },
            },
        },
        {
            encounterID = 2743, encounterIDs = { 2743 },
            name = "Gilnid",
            order = 2000,
            pulls = 1, kills = 1,
            avgLength = 47.0,
            npcs = {
                { id = 1763, name = "Gilnid", displayID = 7124 },
                { id = 1731, name = "Goblin Craftsman", displayID = nil },
            },
            abilities = {
                { spellID = 5159, name = "Melt Ore", source = "Goblin Craftsman", pulls = 1,
                  casts = { { 6.1, "start", 1 }, { 7.6, "success", 1 }, { 36.6, "start", 1 }, { 38.1, "success", 1 } },
                  lanes = { casts = { 6.1, 36.6 }, spread = { 0.0, 0.0 }, support = { 1, 1 }, cast = 1.5 } },
                { spellID = 5213, name = "Molten Metal", source = "Gilnid", pulls = 1,
                  casts = { { 7.6, "start", 1 }, { 9.6, "success", 1 }, { 32.9, "start", 1 }, { 34.9, "success", 1 } },
                  lanes = { casts = { 7.6, 32.9 }, spread = { 0.0, 0.0 }, support = { 1, 1 }, cast = 2.0 } },
            },
        },
        {
            encounterID = 2744, encounterIDs = { 2744 },
            name = "Captain Greenskin",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 647, name = "Captain Greenskin", displayID = 7113 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2745, encounterIDs = { 2745 },
            name = "Mr. Smite",
            order = 4000,
            pulls = 1, kills = 1,
            avgLength = 90.2,
            npcs = {
                { id = 646, name = "Mr. Smite", displayID = 2026 },
            },
            abilities = {
                { spellID = 6432, name = "Smite Stomp", source = "Mr. Smite", pulls = 1,
                  casts = { { 47.3, "success", 1 }, { 68.1, "success", 1 } },
                  lanes = { casts = { 47.3, 68.1 }, spread = { 0.0, 0.0 }, support = { 1, 1 }, cast = 0.0 } },
                { spellID = 3391, name = "Thrash", source = "Mr. Smite", pulls = 1,
                  casts = { { 64.4, "success", 1 } },
                  lanes = { casts = { 64.4 }, spread = { 0.0 }, support = { 1 }, cast = 0.0 } },
                { spellID = 6435, name = "Smite Slam", source = "Mr. Smite", pulls = 1,
                  casts = { { 79.0, "success", 1 }, { 86.4, "success", 1 } },
                  lanes = { casts = { 79.0, 86.4 }, spread = { 0.0, 0.0 }, support = { 1, 1 }, cast = 0.0 } },
            },
        },
        {
            encounterID = 2746, encounterIDs = { 2746 },
            name = "Cookie",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 645, name = "Cookie", displayID = 1305 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2747, encounterIDs = { 2747 },
            name = "Edwin VanCleef",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 639, name = "Edwin VanCleef", displayID = 2029 },
            },
            abilities = {
            },
        },
    },
}
