-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[42903] = {
    name = "Dire Maul: North",
    mapID = 429,
    type = "dungeon",
    level = 59,
    levelMax = 60, levelRange = "59-60",
    pulls = 0,
    bosses = {
        {
            encounterID = 362, encounterIDs = { 362 },
            name = "Guard Mol'dar",
            order = 8000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14326, name = "Guard Mol'dar", displayID = 11561 },
            },
            abilities = {
            },
        },
        {
            encounterID = 363, encounterIDs = { 363 },
            name = "Stomper Kreeg",
            order = 9000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14322, name = "Stomper Kreeg", displayID = 11545 },
            },
            abilities = {
            },
        },
        {
            encounterID = 364, encounterIDs = { 364 },
            name = "Guard Fengus",
            order = 10000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14321, name = "Guard Fengus", displayID = 11561 },
            },
            abilities = {
            },
        },
        {
            encounterID = 365, encounterIDs = { 365 },
            name = "Guard Slip'kik",
            order = 11000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14323, name = "Guard Slip'kik", displayID = 11561 },
            },
            abilities = {
            },
        },
        {
            encounterID = 366, encounterIDs = { 366 },
            name = "Captain Kromcrush",
            order = 12000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14325, name = "Captain Kromcrush", displayID = 11564 },
            },
            abilities = {
            },
        },
        {
            encounterID = 367, encounterIDs = { 367 },
            name = "Cho'Rush the Observer",
            order = 13000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14324, name = "Cho'Rush the Observer", displayID = 11537 },
            },
            abilities = {
            },
        },
        {
            encounterID = 368, encounterIDs = { 368 },
            name = "King Gordok",
            order = 14000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11501, name = "King Gordok", displayID = 11583 },
            },
            abilities = {
            },
        },
    },
}
