-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[42902] = {
    name = "Dire Maul: West",
    mapID = 429,
    type = "dungeon",
    level = 58,
    levelMax = 60, levelRange = "58-60",
    pulls = 0,
    bosses = {
        {
            encounterID = 350, encounterIDs = { 350 },
            name = "Tendris Warpwood",
            order = 3500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11489, name = "Tendris Warpwood", displayID = 14383 },
            },
            abilities = {
            },
        },
        {
            encounterID = 347, encounterIDs = { 347 },
            name = "Illyanna Ravenoak",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11488, name = "Illyanna Ravenoak", displayID = 11270 },
            },
            abilities = {
            },
        },
        {
            encounterID = 348, encounterIDs = { 348 },
            name = "Magister Kalendris",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11487, name = "Magister Kalendris", displayID = 14384 },
            },
            abilities = {
            },
        },
        {
            encounterID = 349, encounterIDs = { 349 },
            name = "Immol'thar",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11496, name = "Immol'thar", displayID = 14173 },
            },
            abilities = {
            },
        },
        {
            encounterID = 361, encounterIDs = { 361 },
            name = "Prince Tortheldrin",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11486, name = "Prince Tortheldrin", displayID = 11256 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2793, encounterIDs = { 2793 },
            name = "Lord Hel'nurath",
            order = 15000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14506, name = "Lord Hel'nurath", displayID = 14556 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2794, encounterIDs = { 2794 },
            name = "Tsu'zee",
            order = 16000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11467, name = "Tsu'zee", displayID = 11250 },
            },
            abilities = {
            },
        },
    },
}
