-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[42901] = {
    name = "Dire Maul: East",
    mapID = 429,
    type = "dungeon",
    level = 55,
    levelMax = 60, levelRange = "55-60",
    pulls = 0,
    bosses = {
        {
            encounterID = 343, encounterIDs = { 343 },
            name = "Zevrim Thornhoof",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11490, name = "Zevrim Thornhoof", displayID = 11335 },
            },
            abilities = {
            },
        },
        {
            encounterID = 344, encounterIDs = { 344 },
            name = "Hydrospawn",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 13280, name = "Hydrospawn", displayID = 5489 },
            },
            abilities = {
            },
        },
        {
            encounterID = 345, encounterIDs = { 345 },
            name = "Lethtendris",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14327, name = "Lethtendris", displayID = 14378 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2792, encounterIDs = { 2792 },
            name = "Pusillin",
            order = 2500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14354, name = "Pusillin", displayID = 7552 },
            },
            abilities = {
            },
        },
        {
            encounterID = 346, encounterIDs = { 346 },
            name = "Alzzin the Wildshaper",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11492, name = "Alzzin the Wildshaper", displayID = 14416 },
            },
            abilities = {
            },
        },
    },
}
