-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[900001] = {
    name = "The Drowned City",
    mapID = 900001,
    type = "dungeon",
    level = 35,
    levelMax = 40, levelRange = "35-40",
    coming = true,   -- on Blizzard's chart, not in the client tables yet
    pulls = 0,
    bosses = {
    },
}
