-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[2998] = {
    name = "Excavation Site: Wetlands",
    mapID = 2998,
    type = "dungeon",
    level = 24,
    levelMax = 29, levelRange = "24-29",
    pulls = 0,
    bosses = {
        {
            encounterID = 3480, encounterIDs = { 3480 },
            name = "Saltspine",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3481, encounterIDs = { 3481 },
            name = "Shadetooth",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3644, encounterIDs = { 3644 },
            name = "Highland Horror",
            order = 1500,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3482, encounterIDs = { 3482 },
            name = "Relic Guardian",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
    },
}
