-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[90] = {
    name = "Gnomeregan",
    mapID = 90,
    type = "dungeon",
    level = 31,
    levelMax = 37, levelRange = "31-37",
    pulls = 0,
    bosses = {
        {
            encounterID = 2768, encounterIDs = { 2768, 2925 },
            name = "Grubbis",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7361, name = "Grubbis", displayID = 6533 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2769, encounterIDs = { 2769, 2928 },
            name = "Viscous Fallout",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7079, name = "Viscous Fallout", displayID = 5497 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2770, encounterIDs = { 2770, 2927 },
            name = "Electrocutioner 6000",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 6235, name = "Electrocutioner 6000", displayID = 6915 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2771, encounterIDs = { 2771, 2899 },
            name = "Crowd Pummeler 9-60",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 6229, name = "Crowd Pummeler 9-60", displayID = 6774 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2772, encounterIDs = { 2772, 2940 },
            name = "Mekgineer Thermaplugg",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7800, name = "Mekgineer Thermaplugg", displayID = 6980 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2935, encounterIDs = { 2935 },
            name = "Mechanical Menagerie",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
    },
}
