-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[900002] = {
    name = "Krol'dok Stronghold",
    mapID = 900002,
    type = "dungeon",
    level = 40,
    levelMax = 45, levelRange = "40-45",
    coming = true,   -- on Blizzard's chart, not in the client tables yet
    pulls = 0,
    bosses = {
    },
}
