-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[349] = {
    name = "Maraudon",
    mapID = 349,
    type = "dungeon",
    level = 48,
    levelMax = 54, levelRange = "48-54",
    pulls = 0,
    bosses = {
        {
            encounterID = 422, encounterIDs = { 422 },
            name = "Noxxion",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 13282, name = "Noxxion", displayID = 11172 },
            },
            abilities = {
            },
        },
        {
            encounterID = 423, encounterIDs = { 423 },
            name = "Razorlash",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12258, name = "Razorlash", displayID = 12389 },
            },
            abilities = {
            },
        },
        {
            encounterID = 427, encounterIDs = { 427 },
            name = "Tinkerer Gizlock",
            order = 1500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 13601, name = "Tinkerer Gizlock", displayID = 7125 },
            },
            abilities = {
            },
        },
        {
            encounterID = 424, encounterIDs = { 424 },
            name = "Lord Vyletongue",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12236, name = "Lord Vyletongue", displayID = 12334 },
            },
            abilities = {
            },
        },
        {
            encounterID = 425, encounterIDs = { 425 },
            name = "Celebras the Cursed",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12225, name = "Celebras the Cursed", displayID = 12350 },
            },
            abilities = {
            },
        },
        {
            encounterID = 426, encounterIDs = { 426 },
            name = "Landslide",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12203, name = "Landslide", displayID = 12293 },
            },
            abilities = {
            },
        },
        {
            encounterID = 428, encounterIDs = { 428 },
            name = "Rotgrip",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 13596, name = "Rotgrip", displayID = 13589 },
            },
            abilities = {
            },
        },
        {
            encounterID = 429, encounterIDs = { 429 },
            name = "Princess Theradras",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12201, name = "Princess Theradras", displayID = 12292 },
            },
            abilities = {
            },
        },
    },
}
