-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[409] = {
    name = "Molten Core",
    mapID = 409,
    type = "raid",
    level = 60,
    levelMax = 60, levelRange = "60-60",
    pulls = 0,
    bosses = {
        {
            encounterID = 663, encounterIDs = { 663 },
            name = "Lucifron",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12118, name = "Lucifron", displayID = 13031 },
            },
            abilities = {
            },
        },
        {
            encounterID = 664, encounterIDs = { 664 },
            name = "Magmadar",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11982, name = "Magmadar", displayID = 10193 },
            },
            abilities = {
            },
        },
        {
            encounterID = 665, encounterIDs = { 665 },
            name = "Gehennas",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12259, name = "Gehennas", displayID = 13030 },
            },
            abilities = {
            },
        },
        {
            encounterID = 666, encounterIDs = { 666 },
            name = "Garr",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12057, name = "Garr", displayID = 12110 },
            },
            abilities = {
            },
        },
        {
            encounterID = 667, encounterIDs = { 667 },
            name = "Shazzrah",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12264, name = "Shazzrah", displayID = 13032 },
            },
            abilities = {
            },
        },
        {
            encounterID = 668, encounterIDs = { 668 },
            name = "Baron Geddon",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12056, name = "Baron Geddon", displayID = 12129 },
            },
            abilities = {
            },
        },
        {
            encounterID = 669, encounterIDs = { 669 },
            name = "Sulfuron Harbinger",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12098, name = "Sulfuron Harbinger", displayID = 13030 },
            },
            abilities = {
            },
        },
        {
            encounterID = 670, encounterIDs = { 670 },
            name = "Golemagg the Incinerator",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11988, name = "Golemagg the Incinerator", displayID = 11986 },
            },
            abilities = {
            },
        },
        {
            encounterID = 671, encounterIDs = { 671 },
            name = "Majordomo Executus",
            order = 8000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 12018, name = "Majordomo Executus", displayID = 12029 },
            },
            abilities = {
            },
        },
        {
            encounterID = 672, encounterIDs = { 672 },
            name = "Ragnaros",
            order = 9000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11502, name = "Ragnaros", displayID = 11121 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3018, encounterIDs = { 3018 },
            name = "The Molten Core",
            order = 10000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 227939, name = "The Molten Core", displayID = 121349 },
            },
            abilities = {
            },
        },
    },
}
