-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[533] = {
    name = "Naxxramas",
    mapID = 533,
    type = "raid",
    level = nil,
    pulls = 0,
    bosses = {
        {
            encounterID = 1107, encounterIDs = { 1107 },
            name = "Anub'Rekhan",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15956, name = "Anub'Rekhan", displayID = 15931 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1110, encounterIDs = { 1110 },
            name = "Grand Widow Faerlina",
            order = 250,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15953, name = "Grand Widow Faerlina", displayID = 15940 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1116, encounterIDs = { 1116 },
            name = "Maexxna",
            order = 312,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15952, name = "Maexxna", displayID = 15928 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1117, encounterIDs = { 1117 },
            name = "Noth the Plaguebringer",
            order = 343,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15954, name = "Noth the Plaguebringer", displayID = 16590 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1112, encounterIDs = { 1112 },
            name = "Heigan the Unclean",
            order = 375,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15936, name = "Heigan the Unclean", displayID = 16309 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1115, encounterIDs = { 1115 },
            name = "Loatheb",
            order = 406,
            pulls = 0, kills = 0,
            npcs = {
                { id = 16011, name = "Loatheb", displayID = 16110 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1113, encounterIDs = { 1113 },
            name = "Instructor Razuvious",
            order = 437,
            pulls = 0, kills = 0,
            npcs = {
                { id = 16061, name = "Instructor Razuvious", displayID = 16582 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1109, encounterIDs = { 1109 },
            name = "Gothik the Harvester",
            order = 500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 16060, name = "Gothik the Harvester", displayID = 16279 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1121, encounterIDs = { 1121 },
            name = "The Four Horsemen",
            order = 562,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 1118, encounterIDs = { 1118 },
            name = "Patchwerk",
            order = 625,
            pulls = 0, kills = 0,
            npcs = {
                { id = 16028, name = "Patchwerk", displayID = 16174 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1111, encounterIDs = { 1111 },
            name = "Grobbulus",
            order = 750,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15931, name = "Grobbulus", displayID = 16035 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1108, encounterIDs = { 1108 },
            name = "Gluth",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15932, name = "Gluth", displayID = 16064 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1120, encounterIDs = { 1120 },
            name = "Thaddius",
            order = 1250,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15928, name = "Thaddius", displayID = 16137 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1119, encounterIDs = { 1119 },
            name = "Sapphiron",
            order = 1500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15989, name = "Sapphiron", displayID = 16033 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1114, encounterIDs = { 1114 },
            name = "Kel'Thuzad",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15990, name = "Kel'Thuzad", displayID = 15945 },
            },
            abilities = {
            },
        },
    },
}
