-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[249] = {
    name = "Onyxia's Lair",
    mapID = 249,
    type = "raid",
    level = nil,
    pulls = 0,
    bosses = {
        {
            encounterID = 1084, encounterIDs = { 1084 },
            name = "Onyxia",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10184, name = "Onyxia", displayID = 8570 },
            },
            abilities = {
            },
        },
    },
}
