-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[389] = {
    name = "Ragefire Chasm",
    mapID = 389,
    type = "dungeon",
    level = 13,
    levelMax = 19, levelRange = "13-19",
    pulls = 0,
    bosses = {
        {
            encounterID = 2732, encounterIDs = { 2732 },
            name = "Oggleflint",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11517, name = "Oggleflint", displayID = 11611 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2733, encounterIDs = { 2733 },
            name = "Taragaman the Hungerer",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11520, name = "Taragaman the Hungerer", displayID = 7970 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2734, encounterIDs = { 2734 },
            name = "Jergosh the Invoker",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11518, name = "Jergosh the Invoker", displayID = 11429 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2735, encounterIDs = { 2735 },
            name = "Bazzalan",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11519, name = "Bazzalan", displayID = 2007 },
            },
            abilities = {
            },
        },
    },
}
