-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[129] = {
    name = "Razorfen Downs",
    mapID = 129,
    type = "dungeon",
    level = 38,
    levelMax = 44, levelRange = "38-44",
    pulls = 0,
    bosses = {
        {
            encounterID = 2780, encounterIDs = { 2780 },
            name = "Tuten'kash",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7355, name = "Tuten'kash", displayID = 7845 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2781, encounterIDs = { 2781 },
            name = "Plaguemaw the Rotting",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7356, name = "Plaguemaw the Rotting", displayID = 6124 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2782, encounterIDs = { 2782 },
            name = "Mordresh Fire Eye",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7357, name = "Mordresh Fire Eye", displayID = 8055 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2783, encounterIDs = { 2783 },
            name = "Ragglesnout",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7354, name = "Ragglesnout", displayID = 11382 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2784, encounterIDs = { 2784 },
            name = "Glutton",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 8567, name = "Glutton", displayID = 7864 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2785, encounterIDs = { 2785 },
            name = "Amnennar the Coldbringer",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7358, name = "Amnennar the Coldbringer", displayID = 7971 },
            },
            abilities = {
            },
        },
    },
}
