-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[47] = {
    name = "Razorfen Kraul",
    mapID = 47,
    type = "dungeon",
    level = 30,
    levelMax = 36, levelRange = "30-36",
    pulls = 0,
    bosses = {
        {
            encounterID = 2773, encounterIDs = { 2773 },
            name = "Roogug",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 6168, name = "Roogug", displayID = 6110 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2774, encounterIDs = { 2774 },
            name = "Aggem Thorncurse",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4424, name = "Aggem Thorncurse", displayID = 6097 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2775, encounterIDs = { 2775 },
            name = "Death Speaker Jargba",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4428, name = "Death Speaker Jargba", displayID = 4644 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2776, encounterIDs = { 2776 },
            name = "Overlord Ramtusk",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4420, name = "Overlord Ramtusk", displayID = 4652 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2777, encounterIDs = { 2777 },
            name = "Agathelos the Raging",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4422, name = "Agathelos the Raging", displayID = 2450 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2778, encounterIDs = { 2778 },
            name = "Charlga Razorflank",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4421, name = "Charlga Razorflank", displayID = 4642 },
            },
            abilities = {
            },
        },
    },
}
