-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[2999] = {
    name = "Ruins of Lordaeron",
    mapID = 2999,
    type = "dungeon",
    level = 15,
    levelMax = 20, levelRange = "15-20",
    pulls = 0,
    bosses = {
        {
            encounterID = 3353, encounterIDs = { 3353 },
            name = "Witherfang",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 250483, name = "Witherfang", displayID = 144189 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3357, encounterIDs = { 3357 },
            name = "The Abandoned",
            order = 250,
            pulls = 0, kills = 0,
            npcs = {
                { id = 250631, name = "The Abandoned", displayID = 138667 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3355, encounterIDs = { 3355 },
            name = "The Butcher",
            order = 500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3886, name = "The Butcher", displayID = 524 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3354, encounterIDs = { 3354 },
            name = "Rath'mael",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 250657, name = "Rath'mael", displayID = 144175 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3408, encounterIDs = { 3408 },
            name = "Lordaeron Captain",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3411, encounterIDs = { 3411 },
            name = "Viktor the Vile",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 256035, name = "Viktor the Vile", displayID = 139455 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3412, encounterIDs = { 3412 },
            name = "Bjork",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 256097, name = "Bjork", displayID = 144170 },
            },
            abilities = {
            },
        },
    },
}
