-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[509] = {
    name = "Ruins of Ahn'Qiraj",
    mapID = 509,
    type = "raid",
    level = nil,
    pulls = 0,
    bosses = {
        {
            encounterID = 718, encounterIDs = { 718 },
            name = "Kurinnaxx",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15348, name = "Kurinnaxx", displayID = 15742 },
            },
            abilities = {
            },
        },
        {
            encounterID = 719, encounterIDs = { 719 },
            name = "General Rajaxx",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15341, name = "General Rajaxx", displayID = 15376 },
            },
            abilities = {
            },
        },
        {
            encounterID = 720, encounterIDs = { 720 },
            name = "Moam",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15340, name = "Moam", displayID = 15392 },
            },
            abilities = {
            },
        },
        {
            encounterID = 721, encounterIDs = { 721 },
            name = "Buru the Gorger",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15370, name = "Buru the Gorger", displayID = 15654 },
            },
            abilities = {
            },
        },
        {
            encounterID = 722, encounterIDs = { 722 },
            name = "Ayamiss the Hunter",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15369, name = "Ayamiss the Hunter", displayID = 15431 },
            },
            abilities = {
            },
        },
        {
            encounterID = 723, encounterIDs = { 723 },
            name = "Ossirian the Unscarred",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15339, name = "Ossirian the Unscarred", displayID = 15432 },
            },
            abilities = {
            },
        },
    },
}
