-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json) + logs WoWCombatLog-093026_191745.txt. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[2999] = {
    name = "Ruins of Lordaeron",
    mapID = 2999,
    type = "dungeon",
    level = 15,
    levelMax = 20, levelRange = "15-20",
    pulls = 5,
    bosses = {
        {
            encounterID = 3353, encounterIDs = { 3353 },
            name = "Witherfang",
            order = 0,
            pulls = 1, kills = 1,
            avgLength = 21.0,
            npcs = {
                { id = 250483, name = "Witherfang", displayID = 144189 },
            },
            abilities = {
                { spellID = 3358, name = "Leech Poison", source = "Witherfang", pulls = 1,
                  casts = { { 1.6, "success", 1 } },
                  lanes = { casts = { 1.6 }, spread = { 0.0 }, support = { 1 }, cast = 0.0 } },
            },
        },
        {
            encounterID = 3357, encounterIDs = { 3357 },
            name = "The Abandoned",
            order = 250,
            pulls = 1, kills = 1,
            avgLength = 28.7,
            npcs = {
                { id = 250631, name = "The Abandoned", displayID = 138667 },
            },
            abilities = {
                { spellID = 1266011, name = "Life Drain", source = "The Abandoned", pulls = 1,
                  casts = { { 9.7, "start", 1 }, { 11.7, "success", 1 }, { 20.6, "start", 1 } },
                  lanes = { casts = { 9.7, 20.6 }, spread = { 0.0, 0.0 }, support = { 1, 1 }, cast = 2.0 } },
                { spellID = 14907, name = "Frost Nova", source = "The Abandoned", pulls = 1,
                  casts = { { 11.7, "success", 1 } },
                  lanes = { casts = { 11.7 }, spread = { 0.0 }, support = { 1 }, cast = 0.0 } },
            },
        },
        {
            encounterID = 3355, encounterIDs = { 3355 },
            name = "The Baron",
            encounterName = "The Butcher",
            order = 500,
            pulls = 1, kills = 1,
            avgLength = 28.3,
            npcs = {
                { id = 250660, name = "The Baron", displayID = 144188 },
            },
            abilities = {
                { spellID = 17307, name = "Knockout", source = "The Baron", pulls = 1,
                  casts = { { 14.0, "success", 1 } },
                  lanes = { casts = { 14.0 }, spread = { 0.0 }, support = { 1 }, cast = 0.0 } },
                { spellID = 5568, name = "Trample", source = "The Baron", pulls = 1,
                  casts = { { 14.6, "success", 1 }, { 26.7, "success", 1 } },
                  lanes = { casts = { 14.6, 26.7 }, spread = { 0.0, 0.0 }, support = { 1, 1 }, cast = 0.0 } },
            },
        },
        {
            encounterID = 3354, encounterIDs = { 3354 },
            name = "Rath'mael",
            order = 1000,
            pulls = 1, kills = 1,
            avgLength = 28.5,
            npcs = {
                { id = 250657, name = "Rath'mael", displayID = 144175 },
            },
            abilities = {
                { spellID = 18399, name = "Flamestrike", source = "Rath'mael", pulls = 1,
                  casts = { { 10.9, "start", 1 }, { 13.9, "success", 1 } },
                  lanes = { casts = { 10.9 }, spread = { 0.0 }, support = { 1 }, cast = 3.0 } },
            },
        },
        {
            encounterID = 3408, encounterIDs = { 3408 },
            name = "Lordaeron Captain",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3411, encounterIDs = { 3411 },
            name = "Viktor the Vile",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 256035, name = "Viktor the Vile", displayID = 139455 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3412, encounterIDs = { 3412 },
            name = "Bjork",
            order = 4000,
            pulls = 1, kills = 1,
            avgLength = 31.9,
            npcs = {
                { id = 256097, name = "Bjork", displayID = 144170 },
                { id = 250689, name = "Living Monstrosity", displayID = 10433 },
            },
            abilities = {
                { spellID = 14099, name = "Mighty Blow", source = "Bjork", pulls = 1,
                  casts = { { 5.0, "success", 1 }, { 11.1, "success", 1 }, { 22.1, "success", 1 }, { 30.6, "success", 1 } },
                  lanes = { casts = { 5.0, 11.1, 22.1, 30.6 }, spread = { 0.0, 0.0, 0.0, 0.0 }, support = { 1, 1, 1, 1 }, cast = 0.0 } },
                { spellID = 1301635, name = "Anti-Magic Shield", source = "Bjork", pulls = 1,
                  casts = { { 14.8, "start", 1 }, { 16.8, "success", 1 } },
                  lanes = { casts = { 14.8 }, spread = { 0.0 }, support = { 1 }, cast = 2.0 } },
                { spellID = 14099, name = "Mighty Blow", source = "Living Monstrosity", pulls = 1,
                  casts = { { 24.6, "success", 1 } },
                  lanes = { casts = { 24.6 }, spread = { 0.0 }, support = { 1 }, cast = 0.0 } },
            },
        },
    },
}
