-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[189] = {
    name = "Scarlet Monastery",
    mapID = 189,
    type = "dungeon",
    level = 31,
    levelMax = 45, levelRange = "31-45",
    pulls = 0,
    bosses = {
        {
            encounterID = 444, encounterIDs = { 444 },
            name = "Interrogator Vishas",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3983, name = "Interrogator Vishas", displayID = 2044 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2779, encounterIDs = { 2779 },
            name = "Bloodmage Thalnos",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4543, name = "Bloodmage Thalnos", displayID = 11396 },
            },
            abilities = {
            },
        },
        {
            encounterID = 446, encounterIDs = { 446 },
            name = "Houndmaster Loksey",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3974, name = "Houndmaster Loksey", displayID = 2040 },
            },
            abilities = {
            },
        },
        {
            encounterID = 447, encounterIDs = { 447 },
            name = "Arcanist Doan",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 6487, name = "Arcanist Doan", displayID = 5266 },
            },
            abilities = {
            },
        },
        {
            encounterID = 448, encounterIDs = { 448 },
            name = "Herod",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3975, name = "Herod", displayID = 2041 },
            },
            abilities = {
            },
        },
        {
            encounterID = 449, encounterIDs = { 449 },
            name = "High Inquisitor Fairbanks",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4542, name = "High Inquisitor Fairbanks", displayID = 2605 },
            },
            abilities = {
            },
        },
        {
            encounterID = 450, encounterIDs = { 450 },
            name = "High Inquisitor Whitemane",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3977, name = "High Inquisitor Whitemane", displayID = 2043 },
            },
            abilities = {
            },
        },
    },
}
