-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[289] = {
    name = "Scholomance",
    mapID = 289,
    type = "dungeon",
    level = 58,
    levelMax = 60, levelRange = "58-60",
    pulls = 0,
    bosses = {
        {
            encounterID = 2805, encounterIDs = { 2805 },
            name = "Kirtonos",
            order = -1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10506, name = "Kirtonos", displayID = 7534 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2804, encounterIDs = { 2804 },
            name = "Jandice Barov",
            order = -500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10503, name = "Jandice Barov", displayID = 11073 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2811, encounterIDs = { 2811 },
            name = "Rattlegore",
            order = -250,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11622, name = "Rattlegore", displayID = 12073 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2809, encounterIDs = { 2809 },
            name = "Marduk Blackpool",
            order = -125,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10433, name = "Marduk Blackpool", displayID = 10248 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2813, encounterIDs = { 2813 },
            name = "Vectus",
            order = -62,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10432, name = "Vectus", displayID = 2606 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3055, encounterIDs = { 3055 },
            name = "Kormok",
            order = -46,
            pulls = 0, kills = 0,
            npcs = {
                { id = 16118, name = "Kormok", displayID = 16020 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2810, encounterIDs = { 2810 },
            name = "Ras Frostwhisperer",
            order = -31,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10508, name = "Ras Frostwhisperer", displayID = 7919 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2803, encounterIDs = { 2803 },
            name = "Instructor Malicia",
            order = -15,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10505, name = "Instructor Malicia", displayID = 11069 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2802, encounterIDs = { 2802 },
            name = "Doctor Theolen Krastinov",
            order = -7,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11261, name = "Doctor Theolen Krastinov", displayID = 10901 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2808, encounterIDs = { 2808 },
            name = "Lorekeeper Polkelt",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10901, name = "Lorekeeper Polkelt", displayID = 11492 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2812, encounterIDs = { 2812 },
            name = "The Ravenian",
            order = 11000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10507, name = "The Ravenian", displayID = 10433 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2807, encounterIDs = { 2807 },
            name = "Lord Alexei Barov",
            order = 11250,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10504, name = "Lord Alexei Barov", displayID = 11072 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2806, encounterIDs = { 2806 },
            name = "Lady Illucia Barov",
            order = 11500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10502, name = "Lady Illucia Barov", displayID = 11835 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2801, encounterIDs = { 2801 },
            name = "Darkmaster Gandling",
            order = 12000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 1853, name = "Darkmaster Gandling", displayID = 11070 },
            },
            abilities = {
            },
        },
    },
}
