-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[33] = {
    name = "Shadowfang Keep",
    mapID = 33,
    type = "dungeon",
    level = 23,
    levelMax = 29, levelRange = "23-29",
    pulls = 0,
    bosses = {
        {
            encounterID = 2748, encounterIDs = { 2748 },
            name = "Rethilgore",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3914, name = "Rethilgore", displayID = 524 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2749, encounterIDs = { 2749 },
            name = "Razorclaw the Butcher",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3886, name = "Razorclaw the Butcher", displayID = 524 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2750, encounterIDs = { 2750 },
            name = "Baron Silverlaine",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3887, name = "Baron Silverlaine", displayID = 3222 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2751, encounterIDs = { 2751 },
            name = "Commander Springvale",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4278, name = "Commander Springvale", displayID = 3223 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2752, encounterIDs = { 2752 },
            name = "Odo the Blindwatcher",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4279, name = "Odo the Blindwatcher", displayID = 522 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2753, encounterIDs = { 2753 },
            name = "Fenrus the Devourer",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4274, name = "Fenrus the Devourer", displayID = 2352 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2754, encounterIDs = { 2754 },
            name = "Wolf Master Nandos",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3927, name = "Wolf Master Nandos", displayID = 11179 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2755, encounterIDs = { 2755 },
            name = "Archmage Arugal",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4275, name = "Archmage Arugal", displayID = 2353 },
            },
            abilities = {
            },
        },
    },
}
