-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[900005] = {
    name = "The Shapers' Terrace",
    mapID = 900005,
    type = "dungeon",
    level = 58,
    levelMax = 60, levelRange = "58-60",
    coming = true,   -- on Blizzard's chart, not in the client tables yet
    pulls = 0,
    bosses = {
    },
}
