-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[34] = {
    name = "Stormwind Stockade",
    mapID = 34,
    type = "dungeon",
    level = 26,
    levelMax = 32, levelRange = "26-32",
    pulls = 0,
    bosses = {
        {
            encounterID = 2756, encounterIDs = { 2756 },
            name = "Targorr the Dread",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 1696, name = "Targorr the Dread", displayID = 517 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2757, encounterIDs = { 2757 },
            name = "Kam Deepfury",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 1666, name = "Kam Deepfury", displayID = 825 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2758, encounterIDs = { 2758 },
            name = "Hamhock",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 1717, name = "Hamhock", displayID = 3250 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2759, encounterIDs = { 2759 },
            name = "Dextren Ward",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 1663, name = "Dextren Ward", displayID = 2149 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2760, encounterIDs = { 2760 },
            name = "Bazil Thredd",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 1716, name = "Bazil Thredd", displayID = 1621 },
            },
            abilities = {
            },
        },
    },
}
