-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[329] = {
    name = "Stratholme",
    mapID = 329,
    type = "dungeon",
    level = 59,
    levelMax = 60, levelRange = "59-60",
    pulls = 0,
    bosses = {
        {
            encounterID = 473, encounterIDs = { 473 },
            name = "Hearthsinger Forresten",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10558, name = "Hearthsinger Forresten", displayID = 10482 },
            },
            abilities = {
            },
        },
        {
            encounterID = 474, encounterIDs = { 474 },
            name = "Timmy the Cruel",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10808, name = "Timmy the Cruel", displayID = 571 },
            },
            abilities = {
            },
        },
        {
            encounterID = 476, encounterIDs = { 476 },
            name = "Malor the Zealous",
            order = 2500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11032, name = "Malor the Zealous", displayID = 10458 },
            },
            abilities = {
            },
        },
        {
            encounterID = 475, encounterIDs = { 475 },
            name = "Cannon Master Willey",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10997, name = "Cannon Master Willey", displayID = 10674 },
            },
            abilities = {
            },
        },
        {
            encounterID = 477, encounterIDs = { 477 },
            name = "Archivist Galford",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10811, name = "Archivist Galford", displayID = 10544 },
            },
            abilities = {
            },
        },
        {
            encounterID = 478, encounterIDs = { 478 },
            name = "Balnazzar",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10813, name = "Balnazzar", displayID = 10691 },
            },
            abilities = {
            },
        },
        {
            encounterID = 472, encounterIDs = { 472 },
            name = "The Unforgiven",
            order = 6500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10516, name = "The Unforgiven", displayID = 10771 },
            },
            abilities = {
            },
        },
        {
            encounterID = 479, encounterIDs = { 479 },
            name = "Baroness Anastari",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10436, name = "Baroness Anastari", displayID = 10698 },
            },
            abilities = {
            },
        },
        {
            encounterID = 480, encounterIDs = { 480 },
            name = "Nerub'enkan",
            order = 8000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10437, name = "Nerub'enkan", displayID = 9793 },
            },
            abilities = {
            },
        },
        {
            encounterID = 481, encounterIDs = { 481 },
            name = "Maleki the Pallid",
            order = 9000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10438, name = "Maleki the Pallid", displayID = 10546 },
            },
            abilities = {
            },
        },
        {
            encounterID = 482, encounterIDs = { 482 },
            name = "Magistrate Barthilas",
            order = 10000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10435, name = "Magistrate Barthilas", displayID = 10433 },
            },
            abilities = {
            },
        },
        {
            encounterID = 483, encounterIDs = { 483 },
            name = "Ramstein the Gorger",
            order = 11000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10439, name = "Ramstein the Gorger", displayID = 12818 },
            },
            abilities = {
            },
        },
        {
            encounterID = 484, encounterIDs = { 484 },
            name = "Baron Rivendare",
            order = 12000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10440, name = "Baron Rivendare", displayID = 10729 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2795, encounterIDs = { 2795 },
            name = "Black Guard Swordsmith",
            order = 13000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11121, name = "Black Guard Swordsmith", displayID = 775 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2796, encounterIDs = { 2796 },
            name = "Crimson Hammersmith",
            order = 14000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11120, name = "Crimson Hammersmith", displayID = 10637 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2797, encounterIDs = { 2797 },
            name = "Ezra Grimm",
            order = 15000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11058, name = "Ezra Grimm", displayID = 10475 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2798, encounterIDs = { 2798 },
            name = "Postmaster Malown",
            order = 16000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11143, name = "Postmaster Malown", displayID = 10669 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2799, encounterIDs = { 2799 },
            name = "Skul",
            order = 17000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10393, name = "Skul", displayID = 2606 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2800, encounterIDs = { 2800 },
            name = "Stonespine",
            order = 18000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 10809, name = "Stonespine", displayID = 7856 },
            },
            abilities = {
            },
        },
    },
}
