-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[109] = {
    name = "Sunken Temple",
    mapID = 109,
    type = "dungeon",
    level = 52,
    levelMax = 58, levelRange = "52-58",
    pulls = 0,
    bosses = {
        {
            encounterID = 492, encounterIDs = { 492, 3583, 2956 },
            name = "Avatar of Hakkar",
            order = -500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 8443, name = "Avatar of Hakkar", displayID = 8053 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2952, encounterIDs = { 2952, 3582, 2814 },
            name = "Atal'alarion",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 8580, name = "Atal'alarion", displayID = 7873 },
            },
            abilities = {
            },
        },
        {
            encounterID = 488, encounterIDs = { 488, 3589 },
            name = "Jammal'an the Prophet",
            order = 500,
            pulls = 0, kills = 0,
            npcs = {
                { id = 5710, name = "Jammal'an the Prophet", displayID = 6708 },
            },
            abilities = {
            },
        },
        {
            encounterID = 486, encounterIDs = { 486, 3588 },
            name = "Dreamscythe",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 5721, name = "Dreamscythe", displayID = 7553 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2953, encounterIDs = { 2953 },
            name = "Festering Rotslime",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 218819, name = "Festering Rotslime", displayID = 119351 },
            },
            abilities = {
            },
        },
        {
            encounterID = 487, encounterIDs = { 487, 3587 },
            name = "Weaver",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 5720, name = "Weaver", displayID = 6375 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2954, encounterIDs = { 2954 },
            name = "Atal'ai Defenders",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 221732, name = "Atal'ai Defenders", displayID = nil },
            },
            abilities = {
            },
        },
        {
            encounterID = 3584, encounterIDs = { 3584, 2959, 493 },
            name = "Shade of Eranikus",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 5709, name = "Shade of Eranikus", displayID = 7806 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2955, encounterIDs = { 2955 },
            name = "Dreamscythe and Weaver",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 3585, encounterIDs = { 3585, 491 },
            name = "Hazzas",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 5722, name = "Hazzas", displayID = 9584 },
            },
            abilities = {
            },
        },
        {
            encounterID = 3586, encounterIDs = { 3586, 490 },
            name = "Morphaz",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 5719, name = "Morphaz", displayID = 7975 },
            },
            abilities = {
            },
        },
        {
            encounterID = 2957, encounterIDs = { 2957 },
            name = "Jammal'an and Ogom",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 2958, encounterIDs = { 2958 },
            name = "Morphaz and Hazzas",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
    },
}
