-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[70] = {
    name = "Uldaman",
    mapID = 70,
    type = "dungeon",
    level = 44,
    levelMax = 50, levelRange = "44-50",
    pulls = 0,
    bosses = {
        {
            encounterID = 547, encounterIDs = { 547 },
            name = "Revelosh",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 6910, name = "Revelosh", displayID = 5945 },
            },
            abilities = {
            },
        },
        {
            encounterID = 548, encounterIDs = { 548 },
            name = "The Lost Dwarves",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 549, encounterIDs = { 549 },
            name = "Ironaya",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7228, name = "Ironaya", displayID = 6089 },
            },
            abilities = {
            },
        },
        {
            encounterID = 1887, encounterIDs = { 1887 },
            name = "Obsidian Sentinel",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7023, name = "Obsidian Sentinel", displayID = 5285 },
            },
            abilities = {
            },
        },
        {
            encounterID = 551, encounterIDs = { 551 },
            name = "Ancient Stone Keeper",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7206, name = "Ancient Stone Keeper", displayID = 10798 },
            },
            abilities = {
            },
        },
        {
            encounterID = 552, encounterIDs = { 552 },
            name = "Galgann Firehammer",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7291, name = "Galgann Firehammer", displayID = 6059 },
            },
            abilities = {
            },
        },
        {
            encounterID = 553, encounterIDs = { 553 },
            name = "Grimlok",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 4854, name = "Grimlok", displayID = 11165 },
            },
            abilities = {
            },
        },
        {
            encounterID = 554, encounterIDs = { 554 },
            name = "Archaedas",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 2748, name = "Archaedas", displayID = 5988 },
            },
            abilities = {
            },
        },
    },
}
