-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[43] = {
    name = "Wailing Caverns",
    mapID = 43,
    type = "dungeon",
    level = 19,
    levelMax = 25, levelRange = "19-25",
    pulls = 0,
    bosses = {
        {
            encounterID = 585, encounterIDs = { 585 },
            name = "Lady Anacondra",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3671, name = "Lady Anacondra", displayID = 4313 },
            },
            abilities = {
            },
        },
        {
            encounterID = 586, encounterIDs = { 586 },
            name = "Lord Cobrahn",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3669, name = "Lord Cobrahn", displayID = 4213 },
            },
            abilities = {
            },
        },
        {
            encounterID = 587, encounterIDs = { 587 },
            name = "Kresh",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3653, name = "Kresh", displayID = 5126 },
            },
            abilities = {
            },
        },
        {
            encounterID = 588, encounterIDs = { 588 },
            name = "Lord Pythas",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3670, name = "Lord Pythas", displayID = 4214 },
            },
            abilities = {
            },
        },
        {
            encounterID = 589, encounterIDs = { 589 },
            name = "Skum",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3674, name = "Skum", displayID = 4203 },
            },
            abilities = {
            },
        },
        {
            encounterID = 590, encounterIDs = { 590 },
            name = "Lord Serpentis",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3673, name = "Lord Serpentis", displayID = 4215 },
            },
            abilities = {
            },
        },
        {
            encounterID = 591, encounterIDs = { 591 },
            name = "Verdan the Everliving",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 5775, name = "Verdan the Everliving", displayID = 4256 },
            },
            abilities = {
            },
        },
        {
            encounterID = 592, encounterIDs = { 592 },
            name = "Mutanus the Devourer",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 3654, name = "Mutanus the Devourer", displayID = 4088 },
            },
            abilities = {
            },
        },
    },
}
