-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[209] = {
    name = "Zul'Farrak",
    mapID = 209,
    type = "dungeon",
    level = 45,
    levelMax = 51, levelRange = "45-51",
    pulls = 0,
    bosses = {
        {
            encounterID = 593, encounterIDs = { 593 },
            name = "Hydromancer Velratha",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7795, name = "Hydromancer Velratha", displayID = 6685 },
            },
            abilities = {
            },
        },
        {
            encounterID = 594, encounterIDs = { 594 },
            name = "Gahz'rilla",
            order = 1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7273, name = "Gahz'rilla", displayID = 7271 },
            },
            abilities = {
            },
        },
        {
            encounterID = 595, encounterIDs = { 595 },
            name = "Antu'sul",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 8127, name = "Antu'sul", displayID = 7353 },
            },
            abilities = {
            },
        },
        {
            encounterID = 596, encounterIDs = { 596 },
            name = "Theka the Martyr",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7272, name = "Theka the Martyr", displayID = 6696 },
            },
            abilities = {
            },
        },
        {
            encounterID = 597, encounterIDs = { 597 },
            name = "Witch Doctor Zum'rah",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7271, name = "Witch Doctor Zum'rah", displayID = 6434 },
            },
            abilities = {
            },
        },
        {
            encounterID = 598, encounterIDs = { 598 },
            name = "Nekrum Gutchewer",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7796, name = "Nekrum Gutchewer", displayID = 6690 },
            },
            abilities = {
            },
        },
        {
            encounterID = 599, encounterIDs = { 599 },
            name = "Shadowpriest Sezz'ziz",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7275, name = "Shadowpriest Sezz'ziz", displayID = 6441 },
            },
            abilities = {
            },
        },
        {
            encounterID = 600, encounterIDs = { 600 },
            name = "Chief Ukorz Sandscalp",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 7267, name = "Chief Ukorz Sandscalp", displayID = 6439 },
            },
            abilities = {
            },
        },
    },
}
