-- GENERATED by build_salusnovus_data.py -- do not edit by hand.
-- Source: client tables (forever_instances.json); no pulls logged yet. Every timing is an observation with its pull count.
local _, ns = ...
ns.Data = ns.Data or {}
ns.Data[309] = {
    name = "Zul'Gurub",
    mapID = 309,
    type = "raid",
    level = 60,
    pulls = 0,
    bosses = {
        {
            encounterID = 785, encounterIDs = { 785 },
            name = "High Priestess Jeklik",
            order = -1000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14517, name = "High Priestess Jeklik", displayID = 15219 },
            },
            abilities = {
            },
        },
        {
            encounterID = 784, encounterIDs = { 784 },
            name = "High Priest Venoxis",
            order = 0,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14507, name = "High Priest Venoxis", displayID = 15217 },
            },
            abilities = {
            },
        },
        {
            encounterID = 786, encounterIDs = { 786 },
            name = "High Priestess Mar'li",
            order = 2000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14510, name = "High Priestess Mar'li", displayID = 15220 },
            },
            abilities = {
            },
        },
        {
            encounterID = 787, encounterIDs = { 787 },
            name = "Bloodlord Mandokir",
            order = 3000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11382, name = "Bloodlord Mandokir", displayID = 11288 },
            },
            abilities = {
            },
        },
        {
            encounterID = 788, encounterIDs = { 788 },
            name = "Edge of Madness",
            order = 4000,
            pulls = 0, kills = 0,
            npcs = {
            },
            abilities = {
            },
        },
        {
            encounterID = 789, encounterIDs = { 789 },
            name = "High Priest Thekal",
            order = 5000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14509, name = "High Priest Thekal", displayID = 15216 },
            },
            abilities = {
            },
        },
        {
            encounterID = 790, encounterIDs = { 790 },
            name = "Gahz'ranka",
            order = 6000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 15114, name = "Gahz'ranka", displayID = 15288 },
            },
            abilities = {
            },
        },
        {
            encounterID = 791, encounterIDs = { 791 },
            name = "High Priestess Arlokk",
            order = 7000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14515, name = "High Priestess Arlokk", displayID = 15218 },
            },
            abilities = {
            },
        },
        {
            encounterID = 792, encounterIDs = { 792 },
            name = "Jin'do the Hexxer",
            order = 8000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 11380, name = "Jin'do the Hexxer", displayID = 11311 },
            },
            abilities = {
            },
        },
        {
            encounterID = 793, encounterIDs = { 793 },
            name = "Hakkar",
            order = 9000,
            pulls = 0, kills = 0,
            npcs = {
                { id = 14834, name = "Hakkar", displayID = 15295 },
            },
            abilities = {
            },
        },
    },
}
