"""Red-green sweep for Salus Novus: copy salusnovus/, break one guarantee, and
expect the suite to go red. A mutation the suite does not notice means the
guarantee is untested, whatever the green run says.

    python salusnovus_test/mutate.py

Each entry is (label, file, old, new); `old` must occur verbatim once.
"""
import io, os, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "salusnovus")

MUTATIONS = [
    # ---- Phase 0: foundation
    ("SyncAnchorOrigin bails on a missing record (landmine 17)", "Core.lua",
     "    if not frame:GetLeft() then return end          -- not laid out yet\n    ns.SaveAnchor(frame, key)",
     "    if not rec then return end\n    if not frame:GetLeft() then return end\n    ns.SaveAnchor(frame, key)"),
    ("SetFontSafe ignores SetFont's return value (landmine 23)", "Fonts.lua",
     "    if ok and applied ~= false then return end\n    ns.fontFellBack",
     "    if ok then return end\n    ns.fontFellBack"),
    ("ApplyAll stops pcalling modules", "Core.lua",
     "        local ok, err = pcall(fn)\n        if ok then\n            applyErrText[i] = nil",
     "        local ok, err = true, nil fn()\n        if ok then\n            applyErrText[i] = nil"),
    ("CopyDefaults silently discards a replaced scalar", "Core.lua",
     "                if dst[k] ~= nil then\n                    SalusNovusDB.replacedScalars",
     "                if false then\n                    SalusNovusDB.replacedScalars"),
    ("RestoreAnchor keeps a junk (non-table) record", "Core.lua",
     "    if p ~= nil and type(p) ~= \"table\" then     -- hand-edited or downgraded\n        SalusNovusDB[key] = nil\n        p = nil\n    end",
     "    if p ~= nil and type(p) ~= \"table\" then p = nil end"),
    ("SnapMovable ignores the snap range", "Core.lua",
     "        local best, bd = nil, range + 0.001",
     "        local best, bd = nil, 1e9"),
    ("Bars stop re-pinning by the growth origin after layout", "Bars.lua",
     "    ns.SyncAnchorOrigin(frame, \"barsPos\")",
     "    -- (removed)"),
    ("ApplyLocks never re-locks", "Core.lua",
     "        if frame.EnableMouse then frame:EnableMouse(unlocked and true or false) end",
     "        if frame.EnableMouse then frame:EnableMouse(true) end"),
    # ---- Phase 1: hub + bars
    ("expiry ignores the hold (bar dropped the moment it lands)", "Timers.lua",
     "            if b.at + (b.hold or 0) <= now then",
     "            if b.at <= now then"),
    ("expiry forgets to fire OnStop", "Timers.lua",
     "                changed = true\n                -- Every removal path fires OnStop",
     "                changed = true\n                if false then"),
    ("SettleDown never stops the ticker", "Timers.lua",
     "    if next(bars) ~= nil or state.active then return end\n    StopTick()",
     "    if true then return end\n    StopTick()"),
    ("a foreign ENCOUNTER_END ends the pull", "Timers.lua",
     "    if state.active and (state.encounterID == nil or id == nil or id == state.encounterID) then",
     "    if state.active then"),
    ("Fire stops pcalling listeners", "Timers.lua",
     "            local ok, err = pcall(fn, ...)",
     "            local ok, err = true, nil fn(...)"),
    ("AddTimer lets NaN through", "Timers.lua",
     "        or duration ~= duration or duration >= math.huge or duration < 0 then   -- 0 = an opener on the pull",
     "        or duration >= math.huge or duration < 0 then"),
    ("FakeBars ignore the data names", "Timers.lua",
     "            name = e and e.name or (\"Ability \" .. i),",
     "            name = (\"Ability \" .. i),"),
    ("Simulate never ends the fight", "Timers.lua",
     "            if state.active and state.encounterID == encounterID then EndEncounter() end",
     "            -- (removed)"),
    ("the intake forgets the hold", "Timers.lua",
     "                      seq = seq, hold = hold }, true)",
     "                      seq = seq }, true)"),
    ("the intake feeds every pull's raw casts instead of the clustered ones", "Timers.lua",
     "        for _, o in ipairs(ns.Schedule.Lanes(state.boss)) do\n            for ci, t in ipairs(o.lanes.casts) do",
     "        for _, o in ipairs(ns.Schedule.Lanes(state.boss)) do\n            for ci, t in ipairs((function() local r = {} for _, c in ipairs(o.a.casts) do r[#r+1] = c[1] end table.sort(r) return r end)()) do"),
    ("reminders stop listening to the hub", "Reminders.lua",
     "        if on then R.OnPull(ns.Timers.BossEncounterID()) else R.OnEnd() end",
     "        -- (removed)"),
    ("a second START keeps the old boss", "Timers.lua",
     "        EndEncounter()\n        StartEncounter(id, name)\n    elseif state.active then",
     "    elseif state.active then"),
    ("a simulation absorbs a real pull", "Timers.lua",
     "    if state.active and (state.simulate or id ~= nil) then",
     "    if state.active and id ~= nil and state.encounterID ~= nil and id ~= state.encounterID then"),
    ("vertical queues reserve no label room per icon", "Queue.lua",
     "            pos = pos + sz + gap + room",
     "            pos = pos + sz + gap"),
    ("bars show a label in a fight", "Bars.lua",
     "        -- No label in a fight at all (Alex): the bars speak for themselves.\n        frame.label:Hide()",
     "        frame.label:SetText(ns.S(boss.name)) frame.label:Show()"),
    ("the low-colour latch is not reset when a slot is re-bound", "Bars.lua",
     "            f.low = low or nil\n",
     "            f.low = f.low or low or nil\n"),
    # ---- Phase 2: reminders anchor
    ("Arm does not trim a lead longer than the offset", "Reminders.lua",
     "    if delay < 0 then\n        lead = math.max(0, lead + delay)\n        delay = 0\n    end",
     "    if delay < 0 then delay = 0 end"),
    ("ENCOUNTER_END leaves a countdown on screen", "Reminders.lua",
     "    state.pullAt = nil\n    CancelAll()\n    ClearShown()\n    wipe(fired)",
     "    state.pullAt = nil\n    CancelAll()\n    wipe(fired)"),
    ("PLAYER_DEAD ignored", "Reminders.lua",
     "ns.On(\"PLAYER_DEAD\", function() CancelAll() ClearShown() end)",
     "-- (removed)"),
    ("a corpse still gets cued", "Reminders.lua",
     "        if UnitIsDeadOrGhost and UnitIsDeadOrGhost(\"player\") then return end",
     "        -- (removed)"),
    ("a live reminder draws inside the preview stage", "Reminders.lua",
     "    if state.preview and not state.sampling then return end",
     "    -- (removed)"),
    ("hidden shipped defaults still fire", "Reminders.lua",
     "        if r.encounterID == encounterID and not hidden[r.id] then out[#out + 1] = r end",
     "        if r.encounterID == encounterID then out[#out + 1] = r end"),
    ("hold is not clamped", "Reminders.lua",
     "    local hold = math.max(0.5, math.min(60, tonumber(r.hold) or opts.hold or 4))",
     "    local hold = tonumber(r.hold) or opts.hold or 4"),
    ("ReminderCancel leaves the old line running", "Reminders.lua",
     "    fired[id] = nil\n    RetractShown(id)",
     "    fired[id] = nil"),
    ("locking an idle reminders anchor leaves it shown", "Reminders.lua",
     "    elseif #active == 0 and not state.preview then\n        frame:Hide()          -- locking an idle anchor hides it at once\n    end",
     "    end"),
    ("secret emote text is read", "Reminders.lua",
     "    if ns.IsSecret(text) or type(text) ~= \"string\" then return end\n    local lower = text:lower()",
     "    if type(text) ~= \"string\" then return end\n    local lower = text:lower()"),
    ("the preview loop keeps sampling after Stop", "Reminders.lua",
     "    if previewLoop then previewLoop:Cancel(); previewLoop = nil end\n    ClearShown()",
     "    ClearShown()"),
    ("a user reminder added mid-pull is not re-armed", "Reminders.lua",
     "    ns.ReminderAdd(boss.encounterID, r)\n    ns.ReminderRearm(r)",
     "    ns.ReminderAdd(boss.encounterID, r)"),
    # ---- Phase 3: options
    ("SaveAnchor writes from inside a preview stage", "Core.lua",
     "    if frame:GetParent() ~= UIParent then return end\n    local point = (frame.__origin",
     "    local point = (frame.__origin"),
    ("Cancel drops the v=2 marker from the snapshot", "Options.lua",
     "    for k, v in pairs(p) do c[k] = v end",
     "    for k, v in pairs(p) do if k ~= \"v\" then c[k] = v end end"),
    ("Cancel keeps the dragged positions", "Options.lua",
     "    if not save and unlockSnapshot then",
     "    if false then"),
    ("a pull leaves unlock mode running", "Options.lua",
     "        if ns.db and ns.db.unlocked then pcall(ExitUnlockMode, true) end\n        if panel and panel:IsShown() then panel:Hide() end",
     "        if panel and panel:IsShown() then panel:Hide() end"),
    ("a pull leaves the panel (and its previews) open", "Options.lua",
     "        if ns.db and ns.db.unlocked then pcall(ExitUnlockMode, true) end\n        if panel and panel:IsShown() then panel:Hide() end",
     "        if ns.db and ns.db.unlocked then pcall(ExitUnlockMode, true) end"),
    ("ReturnToOptions ignores the ESC guard", "Options.lua",
     "    if lastPanelHide and (GetTime() - lastPanelHide) < 0.15 then return end",
     "    -- (removed)"),
    ("the section card anchors to its rows AND the label to the card (anchor cycle)", "Options.lua",
     "        card:SetPoint(\"TOP\", anchor, \"BOTTOM\", 0, -20)",
     "        card:SetPoint(\"TOP\", anchor, \"BOTTOM\", 0, -20)\n        fs:SetPoint(\"BOTTOM\", card, \"TOP\", 0, 0)"),
    ("previews never halt on page hide", "Options.lua",
     "    outer:HookScript(\"OnHide\", function() stage:Halt() end)",
     "    -- (removed)"),
    ("the editor deletes a shipped default outright", "Reminders.lua",
     "            if d.id == id then opts.hidden[id] = true end",
     "            -- (removed)"),
    ("a slider fires onChange before it is primed", "Theme.lua",
     "        if self.quiet or not self.primed then return end",
     "        if self.quiet then return end"),
    # ---- Boss Visualizer (lanes)
    ("VisibleSpan culls on the start point", "Visualizer.lua",
     "    local right = x + math.max(len or 0, halfSpread or 0) * scale\n    local left  = x - (halfSpread or 0) * scale",
     "    local right = x\n    local left  = x"),
    ("the cursor line is anchored by TOP and BOTTOM (x set twice)", "Visualizer.lua",
     "    win.cursor:SetPoint(\"TOPLEFT\", win.axis, \"TOPLEFT\", x, 0)\n    win.cursor:SetPoint(\"BOTTOMLEFT\", win.lanes, \"BOTTOMLEFT\", x + LABEL_W, 0)",
     "    win.cursor:SetPoint(\"TOP\", win.axis, \"TOPLEFT\", x, 0)\n    win.cursor:SetPoint(\"BOTTOM\", win.lanes, \"BOTTOMLEFT\", x + LABEL_W, 0)"),
    # (no mutation for the pooled-mark reset on the reminders lane: that lane
    # is always lane 1 with its own mark pool, so an ability mark can never
    # be re-bound there -- the reset is belt-and-braces, not observable)
    ("instance comparator without `or \"\"`", "Visualizer.lua",
     "        if la ~= lb then return la < lb end\n        return (a.inst.name or \"\") < (b.inst.name or \"\")",
     "        if la ~= lb then return la < lb end\n        return a.inst.name < b.inst.name"),
    ("Remove before Cancel", "Visualizer.lua",
     "            ns.ReminderCancel(form.editing.id)\n            ns.ReminderRemove(state.enc, form.editing.id)",
     "            ns.ReminderRemove(state.enc, form.editing.id)\n            ns.ReminderCancel(form.editing.id)"),
    ("the form's lead is not clamped", "Visualizer.lua",
     "        r.lead = math.max(0, math.min(300, tonumber(form.lead:GetText()) or (ns.db.reminders.lead or 5)))",
     "        r.lead = tonumber(form.lead:GetText()) or (ns.db.reminders.lead or 5)"),
    ("pan slider stays enabled at zoom 1", "Visualizer.lua",
     "    win.pan:SetEnabled(state.zoom > 1)",
     "    win.pan:SetEnabled(true)"),
        ("the one-pull caution comes back on the hover", "Visualizer.lua",
     "                (self.support and self.pulls and self.support < self.pulls)",
     "                (self.pulls and self.pulls <= 1) and \"  (one pull -- timing unconfirmed)\" or (self.support and self.pulls and self.support < self.pulls)"),
    ("a reminder created mid-pull is never armed", "Visualizer.lua",
     "        if r.enabled ~= false then ns.ReminderRearm(r) end\n        form:Hide()",
     "        form:Hide()"),
    ("Lanes clusters casts from the same pull together", "Schedule.lua",
     "        if c and e.t - c.first <= CLUSTER_WINDOW and not c.pulls[e.pull] then",
     "        if c and e.t - c.first <= CLUSTER_WINDOW then"),
    ("fmtExact prints 0:60.0", "Visualizer.lua",
     "    if s >= 59.95 then return fmt(t + 0.05) end\n",
     ""),
    ("closing the window leaves the form open", "Visualizer.lua",
     "    win:SetScript(\"OnHide\", function() if form then form:Hide() end; if ns.ReturnToOptions then ns.ReturnToOptions() end end)",
     "    win:SetScript(\"OnHide\", function() if ns.ReturnToOptions then ns.ReturnToOptions() end end)"),
    # ---- roster
    ("BossByEncounter ignores encounterIDs", "Core.lua",
     "            for _, id in ipairs(b.encounterIDs or {}) do\n                if id == encounterID then return b, inst end\n            end",
     ""),
    ("the sidebar ignores the Raids/Dungeons mode", "Visualizer.lua",
     "        if isRaid == wantRaid then out[#out + 1] = { mapID = mapID, inst = inst } end",
     "        out[#out + 1] = { mapID = mapID, inst = inst }"),
    ("instances sort by name, not level", "Visualizer.lua",
     "        if la ~= lb then return la < lb end\n        return (a.inst.name or \"\") < (b.inst.name or \"\")\n    end)\n    return out\nend\nV.Instances = Instances",
     "        return (a.inst.name or \"\") < (b.inst.name or \"\")\n    end)\n    return out\nend\nV.Instances = Instances"),
    ("reminders keyed by the variant id, not the boss's first", "Reminders.lua",
     "        if on then R.OnPull(ns.Timers.BossEncounterID()) else R.OnEnd() end",
     "        if on then R.OnPull(ns.Timers.EncounterID()) else R.OnEnd() end"),
    # ---- modules
    ("Bars ignore the module switch", "Bars.lua",
     "    return o and o.enabled and ns.ModuleOn(\"bossWarnings\") and true or false",
     "    return o and o.enabled and true or false"),
    ("Reminders ignore the module switch", "Reminders.lua",
     "    return o and o.enabled and ns.ModuleOn(\"bossWarnings\") and true or false",
     "    return o and o.enabled and true or false"),
    ("the sweep ignores the module switch", "Options.lua",
     "            if w.__module and not ns.ModuleOn(w.__module) then\n                if w.SetEnabledState then w:SetEnabledState(false) end\n            elseif",
     "            if false then\n            elseif"),
    ("previews ignore the module switch", "Options.lua",
     "        if mod and not ns.ModuleOn(mod) then",
     "        if false then"),
    ("Unlock Frames ignores the module switch", "Options.lua",
     "        if strip.unlock then strip.unlock:SetEnabledState(not strip.module or ns.ModuleOn(strip.module)) end",
     ""),
    ("the module switch writes nothing", "Options.lua",
     "                ns.db.modules[m.key] = self:GetChecked() and true or false\n                ns.ApplyAll()",
     "                ns.ApplyAll()"),
    ("picker rows are not drawn in their own font", "Options.lua",
     "        ns.SetFontSafe(r.text, 14, \"\", type(v) == \"string\" and v or T.FontPath())",
     "        ns.SetFontSafe(r.text, 14, \"\", T.FontPath())"),
    ("the picker list outlives the window", "Options.lua",
     "        if pickerList then pickerList:Hide() end\n        lastPanelHide = GetTime()",
     "        lastPanelHide = GetTime()"),
    ("a font change re-fonts nothing already on screen", "Fonts.lua",
     "ns.RegisterApply(function() ns.RefontAll() end, \"Fonts\")",
     ""),
    ("explicit-path strings (picker previews) get enrolled and overwritten", "Fonts.lua",
     "    else\n        following[fs] = nil\n    end\n    local want = path or ns.ActiveFont()",
     "    else\n        following[fs] = { size = size, flags = flags }\n    end\n    local want = path or ns.ActiveFont()"),
    ("Theme.SetFont pins the font at creation", "Theme.lua",
     "function T.SetFont(fs, size, flags) ns.SetFontSafe(fs, size, flags or \"\") end",
     "function T.SetFont(fs, size, flags) ns.SetFontSafe(fs, size, flags or \"\", T.FontPath()) end"),
    ("the whole-UI font never restores the originals", "Fonts.lua",
     "                pcall(obj.SetFont, obj, o[1], o[2], o[3] or \"\")\n                uiOriginal[name] = nil",
     "                uiOriginal[name] = nil"),
    ("the whole-UI font forgets the objects' own sizes", "Fonts.lua",
     "                    local okS, applied = pcall(obj.SetFont, obj, want, o[2] or size, o[3] or flags or \"\")",
     "                    local okS, applied = pcall(obj.SetFont, obj, want, 12, \"\")"),
    ("GetFonts ignores LibSharedMedia", "Fonts.lua",
     "    local lsm = LSM()",
     "    local lsm = nil"),
    # ---- queue
    ("queue alpha floor removed", "Queue.lua",
     "            f:SetAlpha(math.max(0.15, a))",
     "            f:SetAlpha(a)"),
    ("queue icons shrink below 16px", "Queue.lua",
     "        sizes[i] = math.max(MIN_ICON, math.floor(s + 0.5))",
     "        sizes[i] = math.floor(s + 0.5)"),
    ("queue never re-pins by its growth origin", "Queue.lua",
     "    ns.SyncAnchorOrigin(frame, \"queuePos\")",
     "    -- (removed)"),
    ("queue ignores desaturate", "Queue.lua",
     "            f.tex:SetDesaturated(opts.desaturate ~= false and i > 1)",
     "            f.tex:SetDesaturated(false)"),
    ("queue edge fraction unclamped", "Queue.lua",
     "                local frac = (dur > 0) and math.max(0, math.min(1, left / dur)) or 0\n                f.edge:SetWidth(math.max(1, f:GetWidth() * frac))",
     "                local frac = (dur > 0) and (left / dur) or 0\n                f.edge:SetWidth(f:GetWidth() * frac)"),
    ("queue ignores the count cap", "Queue.lua",
     "        if #out >= count then break end",
     ""),
    ("queue rewrites the seconds every tick", "Queue.lua",
     "                if secs ~= f.lastSecs then\n                    f.lastSecs = secs\n                    f.timer:SetText(string.format(\"%d\", secs))\n                end",
     "                f.lastSecs = secs\n                f.timer:SetText(string.format(\"%d\", secs))"),
    ("queue ignores the module switch", "Queue.lua",
     "    return o and o.enabled and ns.ModuleOn(\"bossWarnings\") and true or false",
     "    return o and o.enabled and true or false"),
    ("queue keeps drawing in a fight when disabled", "Queue.lua",
     "        if state.preview then return end\n        if not Enabled() then return end\n        Build()",
     "        if state.preview then return end\n        Build()"),
    # ---- Phase 4: polish
    ("wipe watch trusts a false before any true", "Timers.lua",
     "        elseif p == false and state.sawInProgress then",
     "        elseif p == false then"),
    ("wipe watch runs during a simulated fight", "Timers.lua",
     "    if state.simulate or not IsEncounterInProgress then return end",
     "    if not IsEncounterInProgress then return end"),
    # ---- bug hunt (2026-09-19)
    ("a combat res does not re-arm the schedule", "Reminders.lua",
     "ns.On(\"PLAYER_ALIVE\", Resurrected)",
     "-- (removed)"),
    ("a friendly target's cast counts as the boss", "Reminders.lua",
     "        if okA and not ns.IsSecret(hostile) and hostile == false then return end",
     "        if false then return end"),
    ("a secret or missing hostility answer silences cast reminders", "Reminders.lua",
     "        if okA and not ns.IsSecret(hostile) and hostile == false then return end",
     "        if not (okA and hostile == true) then return end"),
    ("/sn reminders formats a nil text", "Reminders.lua",
     "r.arg and (\" \" .. tostring(r.arg)) or \"\", ns.S(r.text)))",
     "r.arg and (\" \" .. tostring(r.arg)) or \"\", r.text))"),
    ("the global font's first-load false is not retried before warning", "Fonts.lua",
     "            if okR and appliedR ~= false then\n                ns.RefontAll(true)\n            else",
     "            if false then\n                ns.RefontAll(true)\n            else"),
    ("a successful font retry re-fonts nothing", "Fonts.lua",
     "            if okR and appliedR ~= false then\n                ns.RefontAll(true)\n            else",
     "            if okR and appliedR ~= false then\n                -- nothing\n            else"),
    ("login does not re-font the strings that follow the global font", "Fonts.lua",
     "    ns.RefontAll(true)\nend)",
     "end)"),
    ("an object born in Salus Novus's font remembers it as its original", "Fonts.lua",
     "                        uiOriginal[name] = { everApplied[path] and StockFont() or path, size, flags }",
     "                        uiOriginal[name] = { path, size, flags }"),
    ("scroll thumbs are painted once and never repainted", "Theme.lua",
     "        T.Paint({ tex = thumb, a = 0.7 })   -- follows an accent change",
     "        local r, g, b = T.Accent()\n        thumb:SetVertexColor(r, g, b, 0.7)"),
    ("a hovered toggle's border stays brighter", "Theme.lua",
     "    cb:SetScript(\"OnLeave\", function(self) self.border:SetColor(1, 1, 1, 0.10) end)   -- the rest colour above",
     "    cb:SetScript(\"OnLeave\", function(self) self.border:SetColor(1, 1, 1, 0.16) end)"),
    ("SnapMovable snaps to a hidden grid", "Core.lua",
     "    if not nx and gridOn then",
     "    if not nx then"),
    ("ParseTime takes anything tonumber takes", "Visualizer.lua",
     "    local bare = s:match(\"^%s*(%d+%.?%d*)%s*$\")\n    return bare and tonumber(bare) or nil",
     "    local n = tonumber(s)\n    if n and n < 0 then return nil end\n    return n"),
    ("the form saves a time past the fight end", "Visualizer.lua",
     "        if trig == \"time\" and t > FightEnd(f) then",
     "        if false then"),
    ("an unloadable spell is re-requested on every answer", "Visualizer.lua",
     "    if requested[id] then return end",
     "    -- (removed)"),
    ("Toggle keeps a variant encounter id and the old view", "Visualizer.lua",
     "            state.enc = boss.encounterID\n            state.offset, state.zoom = 0, 1\n            state.openCard = nil\n            if form then form:Hide() end",
     "            state.enc = encounterID"),
    ("a second Unlock Frames overwrites the snapshot", "Options.lua",
     "    if ns.db.unlocked and unlockSnapshot then",
     "    if false then"),
    ("the module switch leaves Unlock Frames live until the next page change", "Options.lua",
     "                    if strip.unlock and strip.module == m.key then strip.unlock:SetEnabledState(ns.ModuleOn(m.key)) end",
     "                    -- (removed)"),
    ("/sn by hand keeps the return-to-options flag", "Options.lua",
     "        ns.returnToOptions = nil\n        RefreshAll()",
     "        RefreshAll()"),
    ("the lanes area keeps a fixed height, leaving a gap before the abilities", "Visualizer.lua",
     "    win.lanes:SetHeight(math.min(math.max(ly, LANE_H), LANES_MAX))",
     "    win.lanes:SetHeight(LANES_MAX)"),
    # ---- abilities, preview, messages (2026-09-19)
    ("an emptied ability record is kept", "Abilities.lua",
     "    if next(e) == nil then DB()[k] = nil end",
     "    -- (kept)"),
    ("a secret ability key is accepted", "Abilities.lua",
     "    if key == nil or ns.IsSecret(key) then return nil end",
     "    if key == nil then return nil end"),
    ("the rename is ignored by AbilityName", "Timers.lua",
     "        local mine = ns.Abilities.Rename(b.spellID)\n        if mine then return mine end",
     "        -- (ignored)"),
    ("a full role set does not collapse to nil", "Abilities.lua",
     "    if set.tank and set.healer and set.dps then\n        A.Set(key, \"roles\", nil)",
     "    if false then\n        A.Set(key, \"roles\", nil)"),
    ("no assigned role hides role-limited abilities", "Abilities.lua",
     "        if mine == nil then return true end     -- no role assigned: fail open",
     "        if mine == nil then return false end"),
    ("Messages is opt-out instead of opt-in", "Abilities.lua",
     "A.ROUTE_DEFAULT = { queue = true, preview = true, messages = false }",
     "A.ROUTE_DEFAULT = { queue = true, preview = true, messages = true }"),
    ("the queue ignores routing", "Queue.lua",
     "        if ns.Timers.RoutedTo(b, \"queue\") then",
     "        if true then"),
    ("the queue label ignores the ability's colour", "Queue.lua",
     "                f.label:SetTextColor(cr or 1, cg or 1, cb or 1, 1)",
     "                f.label:SetTextColor(1, 1, 1, 1)"),
    ("the bars label ignores the ability's colour", "Bars.lua",
     "            f.text:SetTextColor(cr or 1, cg or 1, cb or 1, 1)",
     "            f.text:SetTextColor(1, 1, 1, 1)"),
    ("OnLand fires on every tick after landing", "Timers.lua",
     "            if not b.landed and b.at <= now then\n                b.landed = true",
     "            if b.at <= now then"),
    ("the preview keeps a landed ability (a NOW line)", "Preview.lua",
     "        if left > 0 and left <= within and ns.Timers.RoutedTo(b, \"preview\") then",
     "        if left > -3 and left <= within and ns.Timers.RoutedTo(b, \"preview\") then"),
    ("the preview ignores routing", "Preview.lua",
     "        if left > 0 and left <= within and ns.Timers.RoutedTo(b, \"preview\") then",
     "        if left > 0 and left <= within then"),
    ("the preview rewrites its seconds every tick", "Preview.lua",
     "            if f.lastSecs ~= e.secs then\n                f.lastSecs = e.secs",
     "            if true then"),
    ("the preview ignores its max", "Preview.lua",
     "        if #out >= max then break end",
     "        -- (uncapped)"),
    ("messages ignore routing", "Messages.lua",
     "    if not ns.Timers.RoutedTo(b, \"messages\") then return end",
     "    -- (unrouted)"),
    ("messages ignore their max", "Messages.lua",
     "    while #active >= max do",
     "    while false do"),
    ("messages survive the end of the fight", "Messages.lua",
     "            for i = #active, 1, -1 do Retire(active[i]) end\n        end\n    end,\n})",
     "        end\n    end,\n})"),
    ("the card editor forgets to sync its controls", "Visualizer.lua",
     "            row.editor:Sync()\n            row.editor:Show()",
     "            row.editor:Show()"),
    ("typing the real name back keeps it as a rename", "Visualizer.lua",
     "        if t == \"\" or t == row.realName then t = nil end",
     "        if t == \"\" then t = nil end"),
    ("section titles sit at the top of their band", "Options.lua",
     "    local drop = math.floor((HEAD_H - h) / 2 + 0.5)   -- whole pixels: a half-pixel row draws the boxes lopsided",
     "    local drop = 0"),
    ("an empty boss still draws its axis and lanes", "Visualizer.lua",
     "    if not has then\n        win.bossTitle:SetText(ns.S(f.name))",
     "    if false then\n        win.bossTitle:SetText(ns.S(f.name))"),
    ("the module-off note gets its wording back", "Options.lua",
     "            self:Suspend(nil)   -- the stage just goes quiet; no wording (Alex)",
     "            self:Suspend(label .. \" is switched off\")"),
    ("the picker's hex box never reaches the sliders", "Theme.lua",
     "    picker.hex:HookScript(\"OnEditFocusLost\", ReadHex)   -- Enter drops focus, which commits once",
     "    -- (hex ignored)"),
    ("the card keeps its swatch without a custom colour", "Visualizer.lua",
     "        self.swatch:SetShown(r ~= nil)     -- the swatch only exists for a custom colour",
     "        self.swatch:Show()"),
    ("only the first word of the title gets the accent initial", "Theme.lua",
     "            for word in text:gmatch(\"%u+\") do",
     "            for word in string.gmatch(text:match(\"^%u+\"), \"%u+\") do"),
    # ---- bug hunt 2 (Sonnet reviewers, 2026-09-19)
    ("shipped default offsets are not scale-compensated", "Core.lua",
     "        frame:SetPoint(defaultPoint, UIParent, relPoint or defaultPoint, (dx or 0) / s0, (dy or 0) / s0)",
     "        frame:SetPoint(defaultPoint, UIParent, relPoint or defaultPoint, dx or 0, dy or 0)"),
    ("a NaN saved position is trusted", "Core.lua",
     "    if p and p.v == 2 and not (Sane(p.x) and Sane(p.y)) then",
     "    if false then"),
    ("the card editor commits against the row's live spell id", "Visualizer.lua",
     "    local function key() return ed.spellID end",
     "    local function key() return row.spellID end"),
    ("Enter commits the rename twice", "Visualizer.lua",
     "    ed.name:HookScript(\"OnEditFocusLost\", Commit)",
     "    ed.name:HookScript(\"OnEnterPressed\", Commit)\n    ed.name:HookScript(\"OnEditFocusLost\", Commit)"),
    ("an open card follows a boss switch", "Visualizer.lua",
     "                    state.openCard = nil     -- an open card does not follow to another boss",
     "                    -- (kept)"),
    ("a negative hold is trusted", "Timers.lua",
     "        b.hold = (hold and hold == hold and hold >= 0) and math.min(60, hold) or 0",
     "        b.hold = extra.hold"),
    ("the intake announces once per cast", "Timers.lua",
     "                      seq = seq, hold = hold }, true)",
     "                      seq = seq, hold = hold })"),
    ("a zero-duration opener is refused", "Timers.lua",
     "        or duration ~= duration or duration >= math.huge or duration < 0 then   -- 0 = an opener on the pull",
     "        or duration ~= duration or duration >= math.huge or duration <= 0 then"),
    ("a spell-less record fails open into Messages", "Timers.lua",
     "    if not b.spellID then return ns.Abilities.ROUTE_DEFAULT[anchor] ~= false end",
     "    if not b.spellID then return true end"),
    ("a /reload while unlocked stays unlocked", "Options.lua",
     "    if ns.db and ns.db.unlocked then ns.db.unlocked = false end",
     "    -- (removed)"),
]


def run(label, fname, old, new):
    tmp = tempfile.mkdtemp(prefix="salusnovus_mut_")
    dst = os.path.join(tmp, "salusnovus")
    shutil.copytree(SRC, dst)
    path = os.path.join(dst, fname)
    src = io.open(path, encoding="utf-8").read()
    if src.count(old) != 1:
        print("  ??  %s -- mutation target found %d times" % (label, src.count(old)))
        shutil.rmtree(tmp, ignore_errors=True)
        return False
    io.open(path, "w", encoding="utf-8").write(src.replace(old, new, 1))
    env = dict(os.environ, MERCURY_PATH=dst)
    p = subprocess.run([sys.executable, os.path.join(HERE, "runner.py")],
                       env=env, capture_output=True, text=True, timeout=300)
    red = p.returncode != 0
    failing = [l.strip() for l in p.stdout.splitlines() if l.strip().startswith(("FAIL", "ERROR"))]
    print("  %s  %s\n        -> %s" % ("RED " if red else "GREEN!", label, "; ".join(failing)[:300] or "no test noticed"))
    shutil.rmtree(tmp, ignore_errors=True)
    return red


# Each mutation is a full suite run (~4-5 s); serially that is ten minutes
# for 140 of them. Runs are independent (own temp copy each), so a pool of
# workers brings it to two or three. Output order follows the table.
WORKERS = max(1, min(8, (os.cpu_count() or 2) - 1))

if __name__ == "__main__":
    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        results = list(pool.map(lambda m: run(*m), MUTATIONS))
    print("\n%d/%d mutations caught" % (sum(results), len(results)))
    sys.exit(0 if all(results) else 1)
