"""Red-green sweep for Salus Novus: copy salusnovus/, break one guarantee, and
expect the suite to go red. A mutation the suite does not notice means the
guarantee is untested, whatever the green run says.

    python salusnovus_test/mutate.py

Each entry is (label, file, old, new); `old` must occur verbatim once.
"""
import io, os, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "salusnovus")

MUTATIONS = [
    # ---- Phase 0: foundation
    ("SyncAnchorOrigin bails on a missing record (landmine 17)", "Core.lua",
     "    if not frame:GetLeft() then return end          -- not laid out yet\n    PinFromCentre(frame, want)",
     "    if not frame:GetLeft() then return end"),
    ("a 0.4.5 chat filter switched off keeps the stock words (seeded back)", "Core.lua",
     "    for k in pairs(ns.defaults.chatFilter.words) do out[k] = false end\n",
     ""),
    ("a fresh anchor is pinned in absolute coordinates at login (stuck when the UI scale settles)", "Core.lua",
     "    frame:SetPoint(point, UIParent, \"CENTER\", dx / s, dy / s)",
     "    frame:SetPoint(point, UIParent, \"BOTTOMLEFT\", x / s, y / s)"),
    ("grid lines are centred on their coordinate again (half-pixel, vanishing)", "Core.lua",
     "        local edge = Px(pos) - (center and pu or 0)",
     "        local edge = pos - thick / 2"),
    ("a scale change never restores the anchors' positions", "Core.lua",
     "            if f.__restore then pcall(f.__restore) end\n",
     ""),
    ("a scale change keeps the stale session pins", "Core.lua",
     "            f.__pin = nil\n            if f.__restore",
     "            if f.__restore"),
    ("a fresh anchor writes a record at login", "Core.lua",
     "    if not frame:GetLeft() then return end          -- not laid out yet\n    PinFromCentre(frame, want)",
     "    if not frame:GetLeft() then return end          -- not laid out yet\n    ns.SaveAnchor(frame, key)"),
    ("SetFontSafe ignores SetFont's return value (landmine 23)", "Fonts.lua",
     "    if ok and applied ~= false then return end\n    ns.fontFellBack",
     "    if ok then return end\n    ns.fontFellBack"),
    ("ApplyAll stops pcalling modules", "Core.lua",
     "        local ok, err = pcall(fn)\n        if ok then\n            applyErrText[i] = nil",
     "        local ok, err = true, nil fn()\n        if ok then\n            applyErrText[i] = nil"),
    ("CopyDefaults silently discards a replaced scalar", "Core.lua",
     "                if dst[k] ~= nil then\n                    SalusNovusDB.replacedScalars",
     "                if false then\n                    SalusNovusDB.replacedScalars"),
    ("RestoreAnchor keeps a junk (non-table) record", "Core.lua",
     "    if p ~= nil and type(p) ~= \"table\" then     -- hand-edited or downgraded\n        SalusNovusDB[key] = nil\n        p = nil\n    end",
     "    if p ~= nil and type(p) ~= \"table\" then p = nil end"),
    ("SnapMovable ignores the snap range", "Core.lua",
     "        local best, bd = nil, range + 0.001",
     "        local best, bd = nil, 1e9"),
    ("Bars stop re-pinning by the growth origin after layout", "Bars.lua",
     "    ns.SyncAnchorOrigin(frame, \"barsPos\")",
     "    -- (removed)"),
    ("ApplyLocks never re-locks", "Core.lua",
     "        if frame.EnableMouse then frame:EnableMouse(unlocked and true or false) end",
     "        if frame.EnableMouse then frame:EnableMouse(true) end"),
    # ---- Phase 1: hub + bars
    ("expiry ignores the hold (bar dropped the moment it lands)", "Timers.lua",
     "            if b.at + (b.hold or 0) <= now then",
     "            if b.at <= now then"),
    ("expiry forgets to fire OnStop", "Timers.lua",
     "                changed = true\n                -- Every removal path fires OnStop",
     "                changed = true\n                if false then"),
    ("SettleDown never stops the ticker", "Timers.lua",
     "    if next(bars) ~= nil or state.active then return end\n    StopTick()",
     "    if true then return end\n    StopTick()"),
    ("a foreign ENCOUNTER_END ends the pull", "Timers.lua",
     "    if state.active and (state.encounterID == nil or id == nil or id == state.encounterID) then",
     "    if state.active then"),
    ("Fire stops pcalling listeners", "Timers.lua",
     "            local ok, err = pcall(fn, ...)",
     "            local ok, err = true, nil fn(...)"),
    ("AddTimer lets NaN through", "Timers.lua",
     "        or duration ~= duration or duration >= math.huge or duration < 0 then   -- 0 = an opener on the pull",
     "        or duration >= math.huge or duration < 0 then"),
    ("FakeBars ignore the data names", "Timers.lua",
     "            name = e and e.name or (\"Ability \" .. i),",
     "            name = (\"Ability \" .. i),"),
    ("Simulate never ends the fight", "Timers.lua",
     "            if state.active and state.encounterID == encounterID then EndEncounter() end",
     "            -- (removed)"),
    ("the intake forgets the hold", "Timers.lua",
     "                      seq = seq, hold = hold }, true)",
     "                      seq = seq }, true)"),
    ("the intake feeds every pull's raw casts instead of the clustered ones", "Timers.lua",
     "        for _, o in ipairs(ns.Schedule.Lanes(state.boss)) do\n            for ci, t in ipairs(o.lanes.casts) do",
     "        for _, o in ipairs(ns.Schedule.Lanes(state.boss)) do\n            for ci, t in ipairs((function() local r = {} for _, c in ipairs(o.a.casts) do r[#r+1] = c[1] end table.sort(r) return r end)()) do"),
    ("reminders stop listening to the hub", "Reminders.lua",
     "        if on then R.OnPull(ns.Timers.BossEncounterID()) else R.OnEnd() end",
     "        -- (removed)"),
    ("a second START keeps the old boss", "Timers.lua",
     "        EndEncounter()\n        StartEncounter(id, name)\n    elseif state.active then",
     "    elseif state.active then"),
    ("a simulation absorbs a real pull", "Timers.lua",
     "    if state.active and (state.simulate or id ~= nil) then",
     "    if state.active and id ~= nil and state.encounterID ~= nil and id ~= state.encounterID then"),
    ("vertical queues reserve no label room per icon", "Queue.lua",
     "            pos = pos + sz + gap + room",
     "            pos = pos + sz + gap"),
    ("bars show a label in a fight", "Bars.lua",
     "        -- No label in a fight at all (Alex): the bars speak for themselves.\n        frame.label:Hide()",
     "        frame.label:SetText(ns.S(boss.name)) frame.label:Show()"),
    ("the low-colour latch is not reset when a slot is re-bound", "Bars.lua",
     "            f.low = low or nil\n",
     "            f.low = f.low or low or nil\n"),
    # ---- Phase 2: reminders anchor
    ("Arm does not trim a lead longer than the offset", "Reminders.lua",
     "    if delay < 0 then\n        lead = math.max(0, lead + delay)\n        delay = 0\n    end",
     "    if delay < 0 then delay = 0 end"),
    ("ENCOUNTER_END leaves a countdown on screen", "Reminders.lua",
     "    state.pullAt = nil\n    CancelAll()\n    ClearShown()\n    wipe(fired)",
     "    state.pullAt = nil\n    CancelAll()\n    wipe(fired)"),
    ("PLAYER_DEAD ignored", "Reminders.lua",
     "ns.On(\"PLAYER_DEAD\", function() CancelAll() ClearShown() end)",
     "-- (removed)"),
    ("a corpse still gets cued", "Reminders.lua",
     "        if UnitIsDeadOrGhost and UnitIsDeadOrGhost(\"player\") then return end",
     "        -- (removed)"),
    ("a live reminder draws inside the preview stage", "Reminders.lua",
     "    if state.preview and not state.sampling then return end",
     "    -- (removed)"),
    ("hidden shipped defaults still fire", "Reminders.lua",
     "        if r.encounterID == encounterID and not hidden[r.id] then out[#out + 1] = r end",
     "        if r.encounterID == encounterID then out[#out + 1] = r end"),
    ("hold is not clamped", "Reminders.lua",
     "    local hold = math.max(0.5, math.min(60, tonumber(r.hold) or opts.hold or 4))",
     "    local hold = tonumber(r.hold) or opts.hold or 4"),
    ("ReminderCancel leaves the old line running", "Reminders.lua",
     "    fired[id] = nil\n    RetractShown(id)",
     "    fired[id] = nil"),
    ("locking an idle reminders anchor leaves it shown", "Reminders.lua",
     "    elseif #active == 0 and not state.preview then\n        frame:Hide()          -- locking an idle anchor hides it at once\n    end",
     "    end"),
    ("secret emote text is read", "Reminders.lua",
     "    if ns.IsSecret(text) or type(text) ~= \"string\" then return end\n    local lower = text:lower()",
     "    if type(text) ~= \"string\" then return end\n    local lower = text:lower()"),
    ("the preview loop keeps sampling after Stop", "Reminders.lua",
     "    if previewLoop then previewLoop:Cancel(); previewLoop = nil end\n    ClearShown()",
     "    ClearShown()"),
    ("a user reminder added mid-pull is not re-armed", "Reminders.lua",
     "    ns.ReminderAdd(boss.encounterID, r)\n    ns.ReminderRearm(r)",
     "    ns.ReminderAdd(boss.encounterID, r)"),
    # ---- Phase 3: options
    ("SaveAnchor writes from inside a preview stage", "Core.lua",
     "    if frame:GetParent() ~= UIParent then return end\n    local point = (frame.__origin",
     "    local point = (frame.__origin"),
    ("Cancel drops the v=2 marker from the snapshot", "Options.lua",
     "    for k, v in pairs(p) do c[k] = v end",
     "    for k, v in pairs(p) do if k ~= \"v\" then c[k] = v end end"),
    ("Cancel keeps the dragged positions", "Options.lua",
     "    if not save and unlockSnapshot then",
     "    if false then"),
    ("a pull leaves unlock mode running", "Options.lua",
     "        if ns.db and ns.db.unlocked then pcall(ExitUnlockMode, true) end\n        if panel and panel:IsShown() then panel:Hide() end",
     "        if panel and panel:IsShown() then panel:Hide() end"),
    ("a pull leaves the panel (and its previews) open", "Options.lua",
     "        if ns.db and ns.db.unlocked then pcall(ExitUnlockMode, true) end\n        if panel and panel:IsShown() then panel:Hide() end",
     "        if ns.db and ns.db.unlocked then pcall(ExitUnlockMode, true) end"),
    ("ReturnToOptions ignores the ESC guard", "Options.lua",
     "    if lastPanelHide and (GetTime() - lastPanelHide) < 0.15 then return end",
     "    -- (removed)"),
    ("the section card anchors to its rows AND the label to the card (anchor cycle)", "Options.lua",
     "        card:SetPoint(\"TOP\", anchor, \"BOTTOM\", 0, -20)",
     "        card:SetPoint(\"TOP\", anchor, \"BOTTOM\", 0, -20)\n        fs:SetPoint(\"BOTTOM\", card, \"TOP\", 0, 0)"),
    ("previews never halt on page hide", "Options.lua",
     "    outer:HookScript(\"OnHide\", function() stage:Halt() end)",
     "    -- (removed)"),
    ("the editor deletes a shipped default outright", "Reminders.lua",
     "            if d.id == id then opts.hidden[id] = true end",
     "            -- (removed)"),
    ("a slider fires onChange before it is primed", "Theme.lua",
     "        if self.quiet or not self.primed then return end",
     "        if self.quiet then return end"),
    # ---- Boss Visualizer (lanes)
    ("VisibleSpan culls on the start point", "Visualizer.lua",
     "    local right = x + math.max(len or 0, halfSpread or 0) * scale\n    local left  = x - (halfSpread or 0) * scale",
     "    local right = x\n    local left  = x"),
    ("the cursor line is anchored by TOP and BOTTOM (x set twice)", "Visualizer.lua",
     "    win.cursor:SetPoint(\"TOPLEFT\", win.axis, \"TOPLEFT\", x, 0)\n    win.cursor:SetPoint(\"BOTTOMLEFT\", win.lanes, \"BOTTOMLEFT\", x + LABEL_W, 0)",
     "    win.cursor:SetPoint(\"TOP\", win.axis, \"TOPLEFT\", x, 0)\n    win.cursor:SetPoint(\"BOTTOM\", win.lanes, \"BOTTOMLEFT\", x + LABEL_W, 0)"),
    # (no mutation for the pooled-mark reset on the reminders lane: that lane
    # is always lane 1 with its own mark pool, so an ability mark can never
    # be re-bound there -- the reset is belt-and-braces, not observable)
    ("instance comparator without `or \"\"`", "Visualizer.lua",
     "        if la ~= lb then return la < lb end\n        return (a.inst.name or \"\") < (b.inst.name or \"\")",
     "        if la ~= lb then return la < lb end\n        return a.inst.name < b.inst.name"),
    ("Remove before Cancel", "Visualizer.lua",
     "            ns.ReminderCancel(form.editing.id)\n            ns.ReminderRemove(state.enc, form.editing.id)",
     "            ns.ReminderRemove(state.enc, form.editing.id)\n            ns.ReminderCancel(form.editing.id)"),
    ("the form's lead is not clamped", "Visualizer.lua",
     "        r.lead = math.max(0, math.min(300, tonumber(form.lead:GetText()) or (ns.db.reminders.lead or 5)))",
     "        r.lead = tonumber(form.lead:GetText()) or (ns.db.reminders.lead or 5)"),
    ("pan slider stays enabled at zoom 1", "Visualizer.lua",
     "    win.pan:SetEnabled(state.zoom > 1)",
     "    win.pan:SetEnabled(true)"),
        ("the one-pull caution comes back on the hover", "Visualizer.lua",
     "                (self.support and self.pulls and self.support < self.pulls)",
     "                (self.pulls and self.pulls <= 1) and \"  (one pull -- timing unconfirmed)\" or (self.support and self.pulls and self.support < self.pulls)"),
    ("a reminder created mid-pull is never armed", "Visualizer.lua",
     "        if r.enabled ~= false then ns.ReminderRearm(r) end\n        form:Hide()",
     "        form:Hide()"),
    ("Lanes clusters casts from the same pull together", "Schedule.lua",
     "        if c and e.t - c.first <= CLUSTER_WINDOW and not c.pulls[e.pull] then",
     "        if c and e.t - c.first <= CLUSTER_WINDOW then"),
    ("fmtExact prints 0:60.0", "Visualizer.lua",
     "    if s >= 59.95 then return fmt(t + 0.05) end\n",
     ""),
    ("closing the window leaves the form open", "Visualizer.lua",
     "    win:SetScript(\"OnHide\", function() if form then form:Hide() end; if ns.ReturnToOptions then ns.ReturnToOptions() end end)",
     "    win:SetScript(\"OnHide\", function() if ns.ReturnToOptions then ns.ReturnToOptions() end end)"),
    # ---- roster
    ("BossByEncounter ignores encounterIDs", "Core.lua",
     "            for _, id in ipairs(b.encounterIDs or {}) do\n                if id == encounterID then return b, inst end\n            end",
     ""),
    ("the sidebar ignores the Raids/Dungeons mode", "Visualizer.lua",
     "        if isRaid == wantRaid then out[#out + 1] = { mapID = mapID, inst = inst } end",
     "        out[#out + 1] = { mapID = mapID, inst = inst }"),
    ("instances sort by name, not level", "Visualizer.lua",
     "        if la ~= lb then return la < lb end\n        return (a.inst.name or \"\") < (b.inst.name or \"\")\n    end)\n    return out\nend\nV.Instances = Instances",
     "        return (a.inst.name or \"\") < (b.inst.name or \"\")\n    end)\n    return out\nend\nV.Instances = Instances"),
    ("reminders keyed by the variant id, not the boss's first", "Reminders.lua",
     "        if on then R.OnPull(ns.Timers.BossEncounterID()) else R.OnEnd() end",
     "        if on then R.OnPull(ns.Timers.EncounterID()) else R.OnEnd() end"),
    # ---- modules
    ("Bars ignore the module switch", "Bars.lua",
     "    return o and o.enabled and ns.ModuleOn(\"bossWarnings\") and true or false",
     "    return o and o.enabled and true or false"),
    ("Reminders ignore the module switch", "Reminders.lua",
     "    return o and o.enabled and ns.ModuleOn(\"bossWarnings\") and true or false",
     "    return o and o.enabled and true or false"),
    ("the sweep ignores the module switch", "Options.lua",
     "            if w.__module and not ns.ModuleOn(w.__module) then\n                if w.SetEnabledState then w:SetEnabledState(false) end\n            elseif",
     "            if false then\n            elseif"),
    ("previews ignore the module switch", "Options.lua",
     "        if mod and not ns.ModuleOn(mod) then",
     "        if false then"),
    ("Unlock Frames ignores the module switch", "Options.lua",
     "        if strip.unlock then strip.unlock:SetEnabledState(not strip.module or ns.ModuleOn(strip.module)) end",
     ""),
    ("the module switch writes nothing", "Options.lua",
     "                ns.db.modules[m.key] = on\n",
     ""),
    ("picker samples are not drawn in their own font", "Options.lua",
     "        ns.SetFontSafe(r.sample, 14, \"\", type(v) == \"string\" and v or T.FontPath())",
     "        ns.SetFontSafe(r.sample, 14, \"\", T.FontPath())"),
    ("the picker list outlives the window", "Options.lua",
     "        if pickerList then pickerList:Hide() end\n        lastPanelHide = GetTime()",
     "        lastPanelHide = GetTime()"),
    ("a font change re-fonts nothing already on screen", "Fonts.lua",
     "ns.RegisterApply(function() ns.RefontAll() end, \"Fonts\")",
     ""),
    ("explicit-path strings (picker previews) get enrolled and overwritten", "Fonts.lua",
     "    else\n        following[fs] = nil\n    end\n    local want = path or ns.ActiveFont()",
     "    else\n        following[fs] = { size = size, flags = flags }\n    end\n    local want = path or ns.ActiveFont()"),
    ("Theme.SetFont pins the font at creation", "Theme.lua",
     "function T.SetFont(fs, size, flags) ns.SetFontSafe(fs, size, flags or \"\") end",
     "function T.SetFont(fs, size, flags) ns.SetFontSafe(fs, size, flags or \"\", T.FontPath()) end"),
    ("the whole-UI font never restores the originals", "Fonts.lua",
     "                pcall(obj.SetFont, obj, o[1], o[2], o[3] or \"\")\n                uiOriginal[name] = nil",
     "                uiOriginal[name] = nil"),
    ("the whole-UI font forgets the objects' own sizes", "Fonts.lua",
     "                    local okS, applied = pcall(obj.SetFont, obj, want, o[2] or size, o[3] or flags or \"\")",
     "                    local okS, applied = pcall(obj.SetFont, obj, want, 12, \"\")"),
    ("GetFonts ignores LibSharedMedia", "Fonts.lua",
     "    local lsm = LSM()",
     "    local lsm = nil"),
    # ---- queue
    ("queue alpha floor removed", "Queue.lua",
     "            f:SetAlpha(math.max(0.15, a))",
     "            f:SetAlpha(a)"),
    ("queue icons shrink below 16px", "Queue.lua",
     "        sizes[i] = math.max(MIN_ICON, math.floor(s + 0.5))",
     "        sizes[i] = math.floor(s + 0.5)"),
    ("queue never re-pins by its growth origin", "Queue.lua",
     "    ns.SyncAnchorOrigin(frame, \"queuePos\")",
     "    -- (removed)"),
    ("queue ignores desaturate", "Queue.lua",
     "            f.tex:SetDesaturated(opts.desaturate ~= false and i > 1)",
     "            f.tex:SetDesaturated(false)"),
    ("queue ignores the count cap", "Queue.lua",
     "        if #out >= count then break end",
     ""),
    ("queue rewrites the seconds every tick", "Queue.lua",
     "                if secs ~= f.lastSecs then\n                    f.lastSecs = secs\n                    f.timer:SetText(string.format(\"%d\", secs))\n                end",
     "                f.lastSecs = secs\n                f.timer:SetText(string.format(\"%d\", secs))"),
    ("queue ignores the module switch", "Queue.lua",
     "    return o and o.enabled and ns.ModuleOn(\"bossWarnings\") and true or false",
     "    return o and o.enabled and true or false"),
    ("queue keeps drawing in a fight when disabled", "Queue.lua",
     "        if state.preview then return end\n        if not Enabled() then return end\n        Build()",
     "        if state.preview then return end\n        Build()"),
    # ---- Phase 4: polish
    ("wipe watch trusts a false before any true", "Timers.lua",
     "        elseif p == false and state.sawInProgress then",
     "        elseif p == false then"),
    ("wipe watch runs during a simulated fight", "Timers.lua",
     "    if state.simulate or not IsEncounterInProgress then return end",
     "    if not IsEncounterInProgress then return end"),
    # ---- bug hunt (2026-09-19)
    ("a combat res does not re-arm the schedule", "Reminders.lua",
     "ns.On(\"PLAYER_ALIVE\", Resurrected)",
     "-- (removed)"),
    ("a friendly target's cast counts as the boss", "Reminders.lua",
     "        if okA and not ns.IsSecret(hostile) and hostile == false then return end",
     "        if false then return end"),
    ("a secret or missing hostility answer silences cast reminders", "Reminders.lua",
     "        if okA and not ns.IsSecret(hostile) and hostile == false then return end",
     "        if not (okA and hostile == true) then return end"),
    ("/sn reminders formats a nil text", "Reminders.lua",
     "r.arg and (\" \" .. tostring(r.arg)) or \"\", ns.S(r.text)))",
     "r.arg and (\" \" .. tostring(r.arg)) or \"\", r.text))"),
    ("the global font's first-load false is not retried before warning", "Fonts.lua",
     "            if okR and appliedR ~= false then\n                ns.RefontAll(true)\n            else",
     "            if false then\n                ns.RefontAll(true)\n            else"),
    ("a successful font retry re-fonts nothing", "Fonts.lua",
     "            if okR and appliedR ~= false then\n                ns.RefontAll(true)\n            else",
     "            if okR and appliedR ~= false then\n                -- nothing\n            else"),
    ("login does not re-font the strings that follow the global font", "Fonts.lua",
     "    ns.RefontAll(true)\nend)",
     "end)"),
    ("an object born in Salus Novus's font remembers it as its original", "Fonts.lua",
     "                        uiOriginal[name] = { everApplied[path] and StockFont() or path, size, flags }",
     "                        uiOriginal[name] = { path, size, flags }"),
    ("scroll thumbs are painted once and never repainted", "Theme.lua",
     "        T.Paint({ tex = thumb, a = 0.7 })   -- follows an accent change",
     "        local r, g, b = T.Accent()\n        thumb:SetVertexColor(r, g, b, 0.7)"),
    ("a hovered toggle's border stays brighter", "Theme.lua",
     "    cb:SetScript(\"OnLeave\", function(self) self.border:SetColor(1, 1, 1, 0.10) end)   -- the rest colour above",
     "    cb:SetScript(\"OnLeave\", function(self) self.border:SetColor(1, 1, 1, 0.16) end)"),
    ("SnapMovable snaps to a hidden grid", "Core.lua",
     "    if not nx and gridOn then",
     "    if not nx then"),
    ("ParseTime takes anything tonumber takes", "Visualizer.lua",
     "    local bare = s:match(\"^%s*(%d+%.?%d*)%s*$\")\n    return bare and tonumber(bare) or nil",
     "    local n = tonumber(s)\n    if n and n < 0 then return nil end\n    return n"),
    ("the form saves a time past the fight end", "Visualizer.lua",
     "        if trig == \"time\" and t > FightEnd(f) then",
     "        if false then"),
    ("an unloadable spell is re-requested on every answer", "Visualizer.lua",
     "    if requested[id] then return end",
     "    -- (removed)"),
    ("Toggle keeps a variant encounter id and the old view", "Visualizer.lua",
     "            state.enc = boss.encounterID\n            state.offset, state.zoom = 0, 1\n            state.openCard = nil\n            if form then form:Hide() end",
     "            state.enc = encounterID"),
    ("a second Unlock Frames overwrites the snapshot", "Options.lua",
     "    if ns.db.unlocked and unlockSnapshot then",
     "    if false then"),
    ("Cancel restores every anchor from Bars's own snapshot, not its own key", "Options.lua",
     "            SalusNovusDB[a.key] = unlockSnapshot[a.key]",
     "            SalusNovusDB[a.key] = unlockSnapshot[\"barsPos\"]"),
    ("the module switch leaves Unlock Frames live until the next page change", "Options.lua",
     "                    if strip.unlock and strip.module == m.key then strip.unlock:SetEnabledState(ns.ModuleOn(m.key)) end",
     "                    -- (removed)"),
    ("/sn by hand keeps the return-to-options flag", "Options.lua",
     "        ns.returnToOptions = nil\n        RefreshAll()",
     "        RefreshAll()"),
    ("the lanes area keeps a fixed height, leaving a gap before the abilities", "Visualizer.lua",
     "    win.lanes:SetHeight(math.min(math.max(ly, LANE_H), LANES_MAX))",
     "    win.lanes:SetHeight(LANES_MAX)"),
    # ---- abilities, preview, messages (2026-09-19)
    ("an emptied ability record is kept", "Abilities.lua",
     "    if next(e) == nil then DB()[k] = nil end",
     "    -- (kept)"),
    ("a secret ability key is accepted", "Abilities.lua",
     "    if key == nil or ns.IsSecret(key) then return nil end",
     "    if key == nil then return nil end"),
    ("the rename is ignored by AbilityName", "Timers.lua",
     "        local mine = ns.Abilities.Rename(b.spellID)\n        if mine then return mine end",
     "        -- (ignored)"),
    ("a full role set does not collapse to nil", "Abilities.lua",
     "    if set.tank and set.healer and set.dps then\n        A.Set(key, \"roles\", nil)",
     "    if false then\n        A.Set(key, \"roles\", nil)"),
    ("no assigned role hides role-limited abilities", "Abilities.lua",
     "        if mine == nil then return true end     -- no role assigned: fail open",
     "        if mine == nil then return false end"),
    ("the route defaults drift (preview on, messages off)", "Abilities.lua",
     "A.ROUTE_DEFAULT = { queue = true, preview = false, messages = true, health = true }",
     "A.ROUTE_DEFAULT = { queue = true, preview = true, messages = false, health = true }"),
    ("the queue ignores routing", "Queue.lua",
     "        if ns.Timers.RoutedTo(b, \"queue\") then",
     "        if true then"),
    ("the queue label ignores the ability's colour", "Queue.lua",
     "                f.label:SetTextColor(cr or 1, cg or 1, cb or 1, 1)",
     "                f.label:SetTextColor(1, 1, 1, 1)"),
    ("the bars label ignores the ability's colour", "Bars.lua",
     "            f.text:SetTextColor(cr or 1, cg or 1, cb or 1, 1)",
     "            f.text:SetTextColor(1, 1, 1, 1)"),
    ("OnLand fires on every tick after landing", "Timers.lua",
     "            if not b.landed and b.at <= now then\n                b.landed = true",
     "            if b.at <= now then"),
    ("the preview keeps a landed ability (a NOW line)", "Preview.lua",
     "        if left > 0 and left <= within and ns.Timers.RoutedTo(b, \"preview\") then",
     "        if left > -3 and left <= within and ns.Timers.RoutedTo(b, \"preview\") then"),
    ("the preview ignores routing", "Preview.lua",
     "        if left > 0 and left <= within and ns.Timers.RoutedTo(b, \"preview\") then",
     "        if left > 0 and left <= within then"),
    ("the preview rewrites its seconds every tick", "Preview.lua",
     "            if f.lastSecs ~= e.secs then\n                f.lastSecs = e.secs",
     "            if true then"),
    ("the preview ignores its max", "Preview.lua",
     "        if #out >= max then break end",
     "        -- (uncapped)"),
    ("messages ignore routing", "Messages.lua",
     "    if not ns.Timers.RoutedTo(b, \"messages\") then return end",
     "    -- (unrouted)"),
    ("messages ignore their max", "Messages.lua",
     "    while #active >= max do",
     "    while false do"),
    ("messages survive the end of the fight", "Messages.lua",
     "            for i = #active, 1, -1 do Retire(active[i]) end\n        end\n    end,\n})",
     "        end\n    end,\n})"),
    ("the card editor forgets to sync its controls", "Visualizer.lua",
     "            row.editor:Sync()\n            row.editor:Show()",
     "            row.editor:Show()"),
    ("typing the real name back keeps it as a rename", "Visualizer.lua",
     "        if t == \"\" or t == row.realName then t = nil end",
     "        if t == \"\" then t = nil end"),
    ("section titles sit at the top of their band", "Options.lua",
     "    local drop = math.floor((HEAD_H - h) / 2 + 0.5)   -- whole pixels: a half-pixel row draws the boxes lopsided",
     "    local drop = 0"),
    ("an empty boss still draws its axis and lanes", "Visualizer.lua",
     "    if not has then\n        win.bossTitle:SetText(ns.S(f.name))",
     "    if false then\n        win.bossTitle:SetText(ns.S(f.name))"),
    ("the module-off note gets its wording back", "Options.lua",
     "            self:Suspend(nil)   -- the stage just goes quiet; no wording (Alex)",
     "            self:Suspend(label .. \" is switched off\")"),
    ("the picker's hex box never reaches the sliders", "Theme.lua",
     "    picker.hex:HookScript(\"OnEditFocusLost\", ReadHex)   -- Enter drops focus, which commits once",
     "    -- (hex ignored)"),
    ("the card keeps its swatch without a custom colour", "Visualizer.lua",
     "        self.swatch:SetShown(r ~= nil)     -- the swatch only exists for a custom colour",
     "        self.swatch:Show()"),
    ("only the first word of the title gets the accent initial", "Theme.lua",
     "            for word in text:gmatch(\"%u+\") do",
     "            for word in string.gmatch(text:match(\"^%u+\"), \"%u+\") do"),
    # ---- bug hunt 2 (Sonnet reviewers, 2026-09-19)
    ("shipped default offsets are not scale-compensated", "Core.lua",
     "        frame:SetPoint(defaultPoint, UIParent, relPoint or defaultPoint, (dx or 0) / s0, (dy or 0) / s0)",
     "        frame:SetPoint(defaultPoint, UIParent, relPoint or defaultPoint, dx or 0, dy or 0)"),
    ("a NaN saved position is trusted", "Core.lua",
     "    if p and p.v == 2 and not (Sane(p.x) and Sane(p.y)) then",
     "    if false then"),
    ("the card editor commits against the row's live spell id", "Visualizer.lua",
     "    local function key() return ed.spellID end",
     "    local function key() return row.spellID end"),
    ("Enter commits the rename twice", "Visualizer.lua",
     "    ed.name:HookScript(\"OnEditFocusLost\", Commit)",
     "    ed.name:HookScript(\"OnEnterPressed\", Commit)\n    ed.name:HookScript(\"OnEditFocusLost\", Commit)"),
    ("an open card follows a boss switch", "Visualizer.lua",
     "                    state.openCard = nil     -- an open card does not follow to another boss",
     "                    -- (kept)"),
    ("a negative hold is trusted", "Timers.lua",
     "        b.hold = (hold and hold == hold and hold >= 0) and math.min(60, hold) or 0",
     "        b.hold = extra.hold"),
    ("the intake announces once per cast", "Timers.lua",
     "                      seq = seq, hold = hold }, true)",
     "                      seq = seq, hold = hold })"),
    ("a zero-duration opener is refused", "Timers.lua",
     "        or duration ~= duration or duration >= math.huge or duration < 0 then   -- 0 = an opener on the pull",
     "        or duration ~= duration or duration >= math.huge or duration <= 0 then"),
    ("a spell-less record fails open into Messages", "Timers.lua",
     "    if not b.spellID then return ns.Abilities.ROUTE_DEFAULT[anchor] ~= false end",
     "    if not b.spellID then return true end"),
    # ---- health bars
    ("health-triggered abilities stay on the lanes and in the timed intake", "Schedule.lua",
     "        if S.IsBossSource(boss, a.source) and not a.health then",
     "        if S.IsBossSource(boss, a.source) then"),
    ("the health marker sits at twice its threshold", "HealthBars.lua",
     '                    m:SetPoint("BOTTOM", r.bar, "BOTTOMLEFT", w * pct / 100, -3)',
     '                    m:SetPoint("BOTTOM", r.bar, "BOTTOMLEFT", w * pct / 50, -3)'),
    ("a refused health value leaves the fill bright", "HealthBars.lua",
     "            r.bar:SetAlpha(0.3)     -- the markers still mean something; the fill does not",
     "            r.bar:SetAlpha(1)"),
    ("the health bar takes the first unit that exists, whatever its name", "HealthBars.lua",
     "    return okN and type(name) == \"string\" and not ns.IsSecret(name) and name == want",
     "    return okN and true"),
    ("the health bar ignores the Health Bars route", "HealthBars.lua",
     "        if ns.Abilities.Routed(a.spellID, \"health\") then out[#out + 1] = a end",
     "        out[#out + 1] = a"),
    ("the health bar outlives the fight", "HealthBars.lua",
     "        if frame then\n            frame:SetAlpha(1)",
     "        if false then\n            frame:SetAlpha(1)"),
    ("unlock shows no placeholder markers on the health bar", "HealthBars.lua",
     "        state.live = { Placeholders()[1] }      -- one sample bar on screen while dragging",
     "        state.live = {}"),
    ("a health ability's card loses its HEALTH tag", "Visualizer.lua",
     "            row.pill:Set(label, 1.00, 0.55, 0.30)",
     "            row.pill:Hide()"),
    ("a multi-threshold card shows one card per marker", "Visualizer.lua",
     "        if not seen[a] then",
     "        if true then"),
    ("a health ability's editor keeps the timed routes", "Visualizer.lua",
     "            cb:SetShown(timed)",
     "            cb:SetShown(true)"),
    ("a /reload while unlocked stays unlocked", "Options.lua",
     "    if ns.db and ns.db.unlocked then ns.db.unlocked = false end",
     "    -- (removed)"),
    # ---- bug hunt 3
    ("AnchorScale takes a zero or negative stored scale at face value", "Core.lua",
     "    if not scale or scale ~= scale or scale <= 0 or scale > 500 then scale = 100 end",
     "    -- (removed)"),
    ("Bars ignores the ability's roles", "Bars.lua",
     "        if RoleOK(b) then",
     "        if true then"),
    ("a health-triggered ability ships with timed lanes as well", "Data/HallOfThanes.lua",
     "                  health = { pct = 48, pulls = 2, samples = { 47.4, 47.8 } } },",
     "                  health = { pct = 48, pulls = 2, samples = { 47.4, 47.8 } },\n"
     "                  lanes = { casts = { 13.4 }, spread = { 2.5 }, support = { 2 }, cast = 0.0 } },"),
    # ---- 2026-09-20 UI trims
    ("ability lanes get their cast count back", "Visualizer.lua",
     '        lane.count:SetText("")          -- no cast count on abilities (Alex)',
     '        lane.count:SetText("x" .. #L.casts)'),
    ("the check box border ignores the pixel unit", "Theme.lua",
     "    b.border:Layout(b, edge, -edge)",
     "    b.border:Layout(b, 1, -1)"),
    ("the check box fill is not snapped to pixels", "Theme.lua",
     "    b.fill:SetSize(box - 2 * inset, box - 2 * inset)",
     "    b.fill:SetSize((size or 18) - 6, (size or 18) - 6)"),
    ("Cancel goes back to the bottom left", "Visualizer.lua",
     '    form.cancel:SetPoint("RIGHT", form.save, "LEFT", -8, 0)',
     '    form.cancel:SetPoint("BOTTOMLEFT", 14, 12)'),
    # ---- bug hunt 4
    ("the health bar keeps a unit that no longer holds the boss", "HealthBars.lua",
     "        if x.unit and UnitIsNamed(x.unit, x.name) then taken[x.unit] = true else x.unit = nil end",
     "        if x.unit then taken[x.unit] = true end"),
    ("the health bar stays armed after the fight", "HealthBars.lua",
     "    if not on then\n        Disarm()",
     "    if not on then"),
    ("any unit's UNIT_HEALTH feeds the bar", "HealthBars.lua",
     "            if x.unit == unit then Feed(x) end",
     "            Feed(x)"),
    ("a plate going away is ignored", "HealthBars.lua",
     "            if x.unit == unit then x.unit = nil; hit = true end",
     "            -- (removed)"),
    ("a route toggled mid-fight does not re-read the health abilities", "HealthBars.lua",
     "    if state.boss then state.live = LiveFor(state.boss, state.live) end",
     "    -- (removed)"),
    ("the slash handler trusts its argument to be a string", "Core.lua",
     '    msg = (type(msg) == "string" and msg or ""):gsub("^%s+", ""):gsub("%s+$", "")',
     '    msg = (msg or ""):gsub("^%s+", ""):gsub("%s+$", "")'),
    ("check boxes are painted once and never on an accent change", "Theme.lua",
     "    T.Paint({ repaint = b })",
     "    -- (removed)"),
    ("sliders are painted once and never on an accent change", "Theme.lua",
     "    T.Paint({ repaint = s })",
     "    -- (removed)"),
    # ---- bug hunt 5
    ("the health bar stays armed with the anchor switched off", "HealthBars.lua",
     "        Disarm()                    -- off mid-fight: nothing runs, not even for a hidden bar",
     "        -- (removed)"),
    ("a multi-threshold health ability draws one marker", "Schedule.lua",
     "            if type(pcts) == \"table\" and #pcts > 1 then",
     "            if false then"),
    ("a colour table without r/g/b reaches the contrast maths", "Core.lua",
     "        if type(c) == \"table\" and type(c.r) == \"number\" and type(c.g) == \"number\" and type(c.b) == \"number\" then",
     "        if type(c) == \"table\" then"),
    ("a reused reminder line keeps its old icon texture", "Reminders.lua",
     "        f.icon:SetTexture(nil)",
     "        -- (removed)"),
    # ---- bug hunt 6
    ("a slider shows a stored value outside its range as-is", "Theme.lua",
     "        if type(lo) == \"number\" and type(hi) == \"number\" then v = math.max(lo, math.min(hi, v)) end",
     "        -- (removed)"),
    ("EndEncounter ends twice", "Timers.lua",
     "    if not state.active then return end   -- wipe watch AND a late END: one end, one OnEncounter(false)",
     "    -- (removed)"),
    ("removing a reminder leaves its timer running", "Reminders.lua",
     "function ns.ReminderRemove(encounterID, id)\n    local t = scheduled[id]\n    if t then pcall(t.Cancel, t); scheduled[id] = nil end",
     "function ns.ReminderRemove(encounterID, id)"),
    # ---- bug hunt 7
    ("ability marks hang off their time by half a mark (left-anchored)", "Visualizer.lua",
     '                m:ClearAllPoints(); m:SetPoint("CENTER", lane.track, "LEFT", x, 0); m:Show()',
     '                m:ClearAllPoints(); m:SetPoint("LEFT", lane.track, "LEFT", x, 0); m:Show()'),
    # ---- 2026-09-20 no drain bar on the queue icons
    ("the queue puts a swipe on every icon by default", "Core.lua",
     'desaturate = true, fade = 50, timeOnIcon = "none", labels = "lead", labelSize = 14,',
     'desaturate = true, fade = 50, timeOnIcon = "swipe", labels = "lead", labelSize = 14,'),
    # ---- 2026-09-20 council Health Bars; grid accent
    ("a council fight gets one bar (every ability under the first boss)", "HealthBars.lua",
     "        local nm = a.source or fallback",
     "        local nm = fallback"),
    ("the stack ignores the direction", "HealthBars.lua",
     '            if Dir() == "up" then',
     "            if false then"),
    ("the stack ignores the gap", "HealthBars.lua",
     "    local gap = opts.spacing or 20",
     "    local gap = 20"),
    ("the name position is always above", "HealthBars.lua",
     '    if p == "inside" or p == "below" or p == "off" then return p end',
     "    -- (removed)"),
    ("ability icons never show", "HealthBars.lua",
     "                    if opts.showIcons then",
     "                    if false then"),
    ("the second boss's UNIT_HEALTH feeds nothing", "HealthBars.lua",
     "            if x.unit == unit then Feed(x) end",
     "            if x.unit == unit and x == state.live[1] then Feed(x) end"),
    ("the grid's minor lines are white again", "Core.lua",
     "        if center then t:SetVertexColor(ar, ag, ab, 0.7) else t:SetVertexColor(ar, ag, ab, 0.18) end",
     "        if center then t:SetVertexColor(ar, ag, ab, 0.7) else t:SetVertexColor(1, 1, 1, 0.08) end"),
    ("a council's second boss is not a health source", "Schedule.lua",
     '        if a.health and type(a.health.pct) == "number" and S.IsBossNpc(boss, a.source) then',
     '        if a.health and type(a.health.pct) == "number" and S.IsBossSource(boss, a.source) then'),
    # ---- 2026-09-20 the picker's palette square
    ("a palette cell does nothing when clicked", "Theme.lua",
     "            picker.SetColor(c[1], c[2], c[3])",
     "            -- (removed)"),
    ("check boxes never snap their position", "Theme.lua",
     "    b:SetPoint(point, rel, relPoint, (x or 0) + dx, (y or 0) + dy)",
     "    -- (removed)"),
    ("the health bar's name is the row's region, under the fill", "HealthBars.lua",
     '    r.name = r.bar:CreateFontString(nil, "OVERLAY")',
     '    r.name = r:CreateFontString(nil, "OVERLAY")'),
    # ---- chat filter
    ("the chat filter ignores the sender's name", "ChatFilter.lua",
     "    return C.Matches(msg) or C.Matches(author)",
     "    return C.Matches(msg)"),
    ("the chat filter matches case-sensitively", "ChatFilter.lua",
     "    local lower = text:lower()\n    for _, w in ipairs(C.List()) do",
     "    local lower = text\n    for _, w in ipairs(C.List()) do"),
    ("the chat filter ignores the Quality of Life switch", "ChatFilter.lua",
     "    if not Enabled() then return false end\n    return C.Matches(msg) or C.Matches(author)",
     "    return C.Matches(msg) or C.Matches(author)"),
    ("Install stacks a filter on every call", "ChatFilter.lua",
     "    if installed then return end\n    if type(ChatFrame_AddMessageEventFilter)",
     "    if type(ChatFrame_AddMessageEventFilter)"),
    ("a false (removed) word still blocks", "ChatFilter.lua",
     "        if type(k) == \"string\" and v == true and k ~= \"\" then",
     "        if type(k) == \"string\" and v ~= nil and k ~= \"\" then"),
    ("removing a word deletes it (re-seeded on the next load)", "ChatFilter.lua",
     "    o.words[w] = false\nend",
     "    o.words[w] = nil\nend"),
    ("AddWord skips the trim", "ChatFilter.lua",
     "    local w = text:lower():gsub(\"^%s+\", \"\"):gsub(\"%s+$\", \"\")",
     "    local w = text:lower()"),
    ("AddWord accepts a duplicate", "ChatFilter.lua",
     "    if o.words[w] == true then return nil end\n",
     ""),
    ("the Chat tab's Remove button forgets to relayout", "Options.lua",
     "                    ns.ChatFilter.RemoveWord(ln.word)\n                    list:Relayout()",
     "                    ns.ChatFilter.RemoveWord(ln.word)"),
    ("the Chat tab's list never resizes", "Options.lua",
     "        self:SetHeight(math.max(1, #words) * WORD_H)",
     "        self:SetHeight(WORD_H)"),
    ("the module switch no longer folds its section", "Options.lua",
     "                SetSectionCollapsed(g.section, not on)\n                LayoutSidebar()",
     "                LayoutSidebar()"),
    ("a fold is not saved", "Options.lua",
     "    ns.db.sidebar.collapsed[SectionKey(section)] = on and true or false\nend",
     "end"),
    ("a folded section's rows stay visible", "Options.lua",
     "            else\n                tab:Hide()\n            end",
     "            end"),
    ("the font button falls back to the raw path", "Options.lua",
     "        local base = v:match(\"([^\\\\/]+)$\") or v\n        return (base:gsub(\"%.[%w]+$\", \"\"))",
     "        return v"),
    ("the font button ignores a case difference in the saved path", "Options.lua",
     "            if type(cand) == \"string\" and cand:lower() == lv and labels[cand] then return labels[cand] end",
     "            if cand == v and labels[cand] then return labels[cand] end"),
    ("picker rows draw the name in the row's own font again", "Options.lua",
     "        ns.SetFontSafe(r.text, 14, \"\", T.FontPath())\n        ns.SetFontSafe(r.sample, 14, \"\", type(v) == \"string\" and v or T.FontPath())",
     "        ns.SetFontSafe(r.text, 14, \"\", type(v) == \"string\" and v or T.FontPath())\n        ns.SetFontSafe(r.sample, 14, \"\", type(v) == \"string\" and v or T.FontPath())"),
    ("Quality of Life off leaves the picked font active", "Fonts.lua",
     "    if ns.ModuleOn and not ns.ModuleOn(\"qol\") then path = nil end\n",
     ""),
    ("abandon skips SetAbandonQuest (the client's arming call)", "Quests.lua",
     "                ql.SetSelectedQuest(q.questID)\n                ql.SetAbandonQuest()\n                ql.AbandonQuest()",
     "                ql.SetSelectedQuest(q.questID)\n                ql.AbandonQuest()"),
    ("abandon ignores CanAbandonQuest", "Quests.lua",
     "    if not ql.CanAbandonQuest then return true end\n    local ok, r = pcall(ql.CanAbandonQuest, id)\n    return not (ok and r == false)",
     "    return true"),
    ("low-level abandons every quest", "Quests.lua",
     "        if q.trivial then out[#out + 1] = q end",
     "        out[#out + 1] = q"),
    ("abandon all ignores the module switch", "Quests.lua",
     "function Q.AbandonAll(list)\n    if not Enabled() then return 0 end\n",
     "function Q.AbandonAll(list)\n"),
    ("a quest turned in while the dialog was open is still sent to the client", "Quests.lua",
     "        if OnLog(ql, q.questID) and CanAbandon(ql, q.questID) then",
     "        if CanAbandon(ql, q.questID) then"),
    ("the Chat page stays 900 tall however long the word list", "Options.lua",
     "        pg:SetHeight(math.max(900, 50 + #words * WORD_H + 46 + 60))\n",
     ""),
    ("a saved capture's missing spell ids are not borrowed (no tooltips)", "Trainer.lua",
     "then return T.BorrowIds(T.DeriveRanks(saved)) end",
     "then return T.DeriveRanks(saved) end"),
    ("Yes re-lists the log instead of abandoning what the dialog counted", "Options.lua",
     "                act(snap)\n",
     "                act()\n"),
    ("the Abandon button skips the confirmation", "Options.lua",
     "            T.Confirm(question(#snap), \"Abandon\", function()\n                act(snap)\n                RefreshAll()\n            end)",
     "            act(snap)\n            RefreshAll()"),
    ("the confirmation's Cancel also runs the action", "Theme.lua",
     "        f.no:SetScript(\"OnClick\", function() f:Hide() end)",
     "        f.no:SetScript(\"OnClick\", function() local fn = f.onYes f:Hide() if fn then fn() end end)"),
    ("a greyed Abandon button still opens the dialog", "Options.lua",
     "            if not self.enabledState then return end\n            local snap = list()",
     "            local snap = list()"),
    ("the guide ignores faction when picking a route", "Guide.lua",
     "        if not faction or not r.faction or r.faction == faction then",
     "        if true then"),
    ("an accept step is never done while the quest is merely in the log", "Guide.lua",
     "    if k == \"accept\" then return OnQuest(step.q) or Flagged(step.q) end",
     "    if k == \"accept\" then return Flagged(step.q) end"),
    ("a do step ignores the finished objective", "Guide.lua",
     "    if k == \"do\" then return Flagged(step.q) or ReadyForTurnIn(step.q) or (OnQuest(step.q) and ObjectiveDone(step.q, step.o)) end",
     "    if k == \"do\" then return Flagged(step.q) or ReadyForTurnIn(step.q) end"),
    ("an uncheckable step never passes on a later checkable one", "Guide.lua",
     "            done = sk[i] or i < lastDone\n",
     "            done = sk[i]\n"),
    ("the distance is computed across maps", "Guide.lua",
     "    if map ~= step.m or not x then return nil end",
     "    if not x then return nil end"),
    ("the arrow forgets the player's facing", "Arrow.lua",
     "    local rot = bearing - Facing()",
     "    local rot = bearing"),
    ("the arrow's bearing swaps north and west", "Arrow.lua",
     "        return math.atan2(dW, dN), math.sqrt(dN * dN + dW * dW)",
     "        return math.atan2(dN, dW), math.sqrt(dN * dN + dW * dW)"),
    ("the map-space fallback crosses maps", "Arrow.lua",
     "    if map ~= step.m or not (C_Map and C_Map.GetMapWorldSize) then return nil end",
     "    if not (C_Map and C_Map.GetMapWorldSize) then return nil end"),
    ("the arrow ignores its own setting", "Arrow.lua",
     "    return o and o.enabled ~= false and o.arrow ~= false and ns.ModuleOn(\"leveling\") and true or false",
     "    return o and o.enabled ~= false and ns.ModuleOn(\"leveling\") and true or false"),
    ("the arrow stays up with no current step", "Arrow.lua",
     "    if unlocked or (Enabled() and Step()) then",
     "    if unlocked or Enabled() then"),
    ("the editor forgets to log an edit", "RouteEditor.lua",
     "    Log(route, { op = \"del\", at = i })\n",
     ""),
    ("the editor inserts after the current step instead of before", "RouteEditor.lua",
     "    local at = (ns.Guide.CurrentIndex(route) or (#route.steps + 1)) - 1",
     "    local at = ns.Guide.CurrentIndex(route) or #route.steps"),
    ("skips do not follow a delete", "Guide.lua",
     "            if i == at then j = nil elseif i > at then j = i - 1 end",
     "            j = i"),
    ("the Steps tab does not mark the current step", "Options.lua",
     "            if i == cur then\n                local r, g, b = T.Accent()\n                ln.text:SetTextColor(r, g, b, 1)\n            elseif cur and i < cur then",
     "            if cur and i < cur then"),
    ("the builder inserts before the current step instead of appending", "RouteEditor.lua",
     "    if not E.Insert(route, #route.steps, step) then return nil end\n    return #route.steps",
     "    return E.InsertHere(route, kind, questID, text)"),
    ("EnsureRoute never logs the new route", "RouteEditor.lua",
     "    Log(route, { op = \"new\", name = route.name, faction = faction, race = race, class = class, map = route.map, level = level })\n",
     ""),
    ("a go step never arrives", "Arrow.lua",
     "    if step and step.k == \"go\" and dist <= ns.Guide.ARRIVE then",
     "    if false then"),
    ("a do step shows its stored text even while the quest is in the log", "Guide.lua",
     "        local live = OnQuest(step.q) and LiveObjective(step.q, step.o)\n        if live then return \"Complete objective: \" .. live end\n",
     ""),
    ("the builder's do step always points at objective 1", "RouteEditor.lua",
     "                    if type(ob) == \"table\" and ob.finished ~= true then s.o = i break end",
     "                    if type(ob) == \"table\" then s.o = i break end"),
    ("Move forgets to log", "RouteEditor.lua",
     "    Log(route, { op = \"mv\", at = i, to = j })\n",
     ""),
    ("skips do not follow a move", "Guide.lua",
     "        if op == \"mv\" then\n            if i == at then\n                j = to\n            else",
     "        if false then\n            if i == at then\n                j = to\n            else"),
    ("a drop ignores the row's own removal when computing the landing index", "Options.lua",
     "                if to > d.from then to = to - 1 end\n",
     ""),
    ("an insert ignores Above/Below", "Options.lua",
     "                local after = (place == \"above\") and (sel - 1) or sel",
     "                local after = sel"),
    ("DeleteRoute forgets to log the drop", "RouteEditor.lua",
     "    Log(route, { op = \"drop\" })\n",
     ""),
    ("NewRoute does not select the new route", "RouteEditor.lua",
     "    if ns.db and ns.db.guide then ns.db.guide.route = slug end     -- follow it now\n",
     ""),
    ("best match ignores the level band", "Guide.lua",
     "            if type(lv) == \"table\" and Num(lv[1]) and Num(lv[2]) and level >= lv[1] and level <= lv[2] then score = score + 1 end\n",
     ""),
    ("Delete route skips the confirmation", "Options.lua",
     "        T.Confirm((\"Delete the route \\\"%s\\\" and its %d step%s?\"):format(r.name or r.slug, #r.steps, #r.steps == 1 and \"\" or \"s\"), \"Delete\", function()\n            E.DeleteRoute(r)\n            if O.stepsList then O.stepsList:Select(nil) end\n            RefreshAll()\n        end)",
     "        E.DeleteRoute(r)\n        RefreshAll()"),
    ("the header rule is not tinted with the accent", "Options.lua",
     "    T.Paint({ tex = card.rule, a = 1 })\n",
     ""),
    ("the header title stays white", "Options.lua",
     "    T.Paint({ repaint = { Repaint = function() local r, g, b = T.Accent() fs:SetTextColor(r, g, b, 1) end } })\n",
     ""),
    ("the header band is hidden again", "Options.lua",
     "    card.head:Show()\n    card.rule = card:CreateTexture(nil, \"ARTWORK\")",
     "    card.head:Hide()\n    card.rule = card:CreateTexture(nil, \"ARTWORK\")"),
    ("the trainer capture leaves the window's filter changed", "Trainer.lua",
     "    for f, v in pairs(before) do pcall(SetTrainerServiceTypeFilter, f, v) end\n",
     ""),
    ("the trainer capture drops a false filter value", "Trainer.lua",
     "                before[f] = v and true or false                 -- a false must be put back too",
     "                before[f] = v or nil"),
    ("a higher known rank does not cover the lower ranks", "Trainer.lua",
     "    return have >= r\nend\n\n--- A prerequisite",
     "    return have == r\nend\n\n--- A prerequisite"),
    ("an unmet prerequisite still counts as learnable", "Trainer.lua",
     "            if levelOk and #d.missing == 0 then",
     "            if levelOk then"),
    ("a profession trainer is captured as the class catalogue", "Trainer.lua",
     "        if ok and trade then return nil, \"tradeskill trainer\" end\n",
     ""),
    ("derived ranks ignore the level order", "Trainer.lua",
     "            table.sort(rest, function(x, y)\n                local lx, ly = x.level or 0, y.level or 0\n                if lx ~= ly then return lx < ly end\n                return (x.cost or 0) < (y.cost or 0)\n            end)",
     ""),
    ("derived ranks ignore the prerequisite text", "Trainer.lua",
     "                    if rname == name and rk then got = tonumber(rk) + 1 end",
     ""),
    ("the spellbook's rank is never asked of the spell itself", "Trainer.lua",
     "                    if not r and sb.GetSpellBookItemInfo then",
     "                    if false then"),
    ("the tab row may end up under the list (icons cut off)", "TrainerUI.lua",
     "    if host.tabs and host.tabs.GetFrameLevel and host.tabs:GetFrameLevel() <= lvl then host.tabs:SetFrameLevel(lvl + 1) end\n",
     ""),
    ("the list is levelled only at build, not when shown", "TrainerUI.lua",
     "    Layer()\n    content:Show()",
     "    content:Show()"),
    ("a live capture never borrows the shipped ids", "Trainer.lua",
     "    T.BorrowIds(cap)\n",
     ""),
    ("an empty group still shows its header", "TrainerUI.lua",
     "        if #list > 0 then\n            used = used + 1\n            local r = Row(used)\n            ShowHead(r, title)",
     "        if true then\n            used = used + 1\n            local r = Row(used)\n            ShowHead(r, title)"),
    ("Blizzard's selected tab keeps its gold frame under ours", "TrainerUI.lua",
     "    content:Show()\n    DimTheirs()",
     "    content:Show()"),
    ("their gold frame never comes back", "TrainerUI.lua",
     "        for _, tex in ipairs(dimmed) do tex:Show() end\n",
     ""),
    ("their tab click restores the old selection too (double gold)", "TrainerUI.lua",
     "    UndimTheirs(clicked == nil or clicked == dimmedTab)",
     "    UndimTheirs(true)"),
    ("clicking the dimmed tab back forgets its frame", "TrainerUI.lua",
     "    UndimTheirs(clicked == nil or clicked == dimmedTab)",
     "    UndimTheirs(clicked == nil)"),
    ("the active tab never shows Blizzard's frame", "TrainerUI.lua",
     "        self.frame:SetShown(self.active)\n        self.glowTex:SetShown(self.active)",
     "        self.frame:SetShown(false)\n        self.glowTex:SetShown(false)"),
    ("the tab sits 6px after the last, not 1", "TrainerUI.lua",
     "tab:SetPoint(\"LEFT\", last, \"RIGHT\", 1, 0)",
     "tab:SetPoint(\"LEFT\", last, \"RIGHT\", 6, 0)"),
    ("leaving a row keeps its pop", "TrainerUI.lua",
     "        r.hover:Hide()\n        r.edge:Hide()\n        r.name:SetTextColor(Th.TEXT[1], Th.TEXT[2], Th.TEXT[3], 1)",
     "        r.name:SetTextColor(Th.TEXT[1], Th.TEXT[2], Th.TEXT[3], 1)"),
    ("the tooltip never uses the spell id", "TrainerUI.lua",
     "        pcall(tt.SetSpellByID, tt, e.spell)",
     "        tt:AddLine(e.name, 1, 1, 1)"),
    ("the spell id is never read from the link", "Trainer.lua",
     "                    if id then e.spell = id end",
     ""),
    ("clicking our tab again toggles it off", "TrainerUI.lua",
     "    tab:SetScript(\"OnClick\", function() if not (content and content:IsShown()) then ShowOurs() end end)",
     "    tab:SetScript(\"OnClick\", function() if content and content:IsShown() then ShowTheirs() else ShowOurs() end end)"),
    ("the tab is placed once at build and never when the book shows", "TrainerUI.lua",
     "            PlaceTab()\n            C_Timer.After(0, PlaceTab)",
     ""),
    ("the tab re-places on show only while unplaced (sits on a later tab)", "TrainerUI.lua",
     "            PlaceTab()\n            C_Timer.After(0, PlaceTab)",
     "            if not tab.placed then PlaceTab() end"),
    ("a refresh never re-places the tab", "TrainerUI.lua",
     "ns.Trainer.Refresh = function() UI.Refresh() if tab then PlaceTab() tab:Update() end end",
     "ns.Trainer.Refresh = function() UI.Refresh() if tab then tab:Update() end end"),
    ("the tab search counts our own tab (anchors to itself on re-place)", "TrainerUI.lua",
     "        if k ~= tab and k.IsShown and k:IsShown() and k.GetObjectType",
     "        if k.IsShown and k:IsShown() and k.GetObjectType"),
    ("late-made Blizzard tabs are never hooked", "TrainerUI.lua",
     "            if k ~= tab and not hooked[k] and k.HookScript",
     "            if false and k ~= tab and not hooked[k] and k.HookScript"),
    ("the spellbook list stays 1px wide (icons only in game)", "TrainerUI.lua",
     "    local function FitList() content.list:SetWidth(math.max(1, content.scroll:GetWidth() or 0)) end",
     "    local function FitList() end"),
    ("an unreadable filter is still forced on", "Trainer.lua",
     "                pcall(SetTrainerServiceTypeFilter, f, true)     -- only what can be put back is touched\n            end",
     "            end\n            pcall(SetTrainerServiceTypeFilter, f, true)"),
    ("ghost rows keep their stale entry", "TrainerUI.lua",
     "    for i = used + 1, #rows do Reset(rows[i]) rows[i]:Hide() end",
     "    for i = used + 1, #rows do rows[i]:Hide() end"),
    ("the list hides with a row tooltip left up", "TrainerUI.lua",
     "        for _, r in ipairs(rows) do DropTip(r) end\n",
     ""),
    ("the probe reads the trainer but saves nothing", "Probe.lua",
     "        local cap, why = ns.Trainer.Capture(true)",
     "        local cap, why = ns.Trainer.ReadTrainer()"),
    ("a level-up no longer refreshes the spellbook tab", "Trainer.lua",
     "    if T.Refresh then T.Refresh() end\nend)",
     "end)"),
    ("our tab never hides the spellbook page", "TrainerUI.lua",
     "    if host.page and host.page:IsShown() then host.page:Hide() hidPage = true end\n",
     ""),
    ("a Blizzard tab does not put the page back", "TrainerUI.lua",
     "                k:HookScript(\"OnClick\", function(self) ShowTheirs(self) end)\n",
     ""),
    ("their disabled selected tab stays dead under ours", "TrainerUI.lua",
     "        dimmedTab:Enable()\n        dimmedWasDisabled = true",
     "        dimmedWasDisabled = true"),
    ("the re-enabled tab is never disabled again", "TrainerUI.lua",
     "        if dimmedWasDisabled and dimmedTab and dimmedTab.Disable then dimmedTab:Disable() end\n",
     ""),
    ("the tab ignores its switch", "TrainerUI.lua",
     "        tab:SetShown(on)\n",
     ""),
    ("a plain window title hangs off the empty initial again (pokes above the band)", "Theme.lua",
     "            self.title:ClearAllPoints()\n            self.title:SetPoint(\"TOPLEFT\", header, \"TOPLEFT\", 22, -6)\n",
     ""),
    ("section titles go back to the left", "Options.lua",
     "    fs:SetJustifyH(\"CENTER\")\n    local wide = column == \"wide\"",
     "    fs:SetJustifyH(\"LEFT\")\n    local wide = column == \"wide\""),
    ("a secret chat line reaches :lower()", "ChatFilter.lua",
     "    if type(text) ~= \"string\" or ns.IsSecret(text) then return false end",
     "    if type(text) ~= \"string\" then return false end"),
]


# Which test groups can catch a break in each file. A mutation runs only
# those (seconds, not minutes); a survivor is then re-checked against the
# FULL suite before it is called a survivor, so the map can be incomplete
# without a wrong answer -- an incomplete map only costs time. A file not
# listed runs the full suite.
FILE_GROUPS = {
    "Theme.lua":       "theme,options,fonts,font,chat,bughunt,quests,lane09,h9lane03",
    "Options.lua":     "options,chat,quests,routes,editor,sidebar,modules,theme,fonts,font,guide,trainer,lane05,lane08,h9lane03,h9lane02,bughunt,bughunt3",
    "Timers.lua":      "hub,bars,queue,health,reminders,data,abilities,bughunt,bughunt3,bughunt4,bughunt5,bughunt6",
    "Reminders.lua":   "reminders,visualizer,bughunt,bughunt3,bughunt4,bughunt5,bughunt6",
    "HealthBars.lua":  "health,anchors,bughunt3",
    "Visualizer.lua":  "visualizer,abilities,theme,polish,bughunt,bughunt3",
    "Queue.lua":       "queue,anchors,bughunt,bughunt3",
    "Fonts.lua":       "fonts,font,theme,chat,bughunt",
    "Bars.lua":        "bars,anchors,bughunt,bughunt3",
    "Messages.lua":    "anchors,bughunt,bughunt3",
    "Preview.lua":     "anchors,bughunt,bughunt3",
    "Abilities.lua":   "abilities,visualizer,bughunt3",
    "Schedule.lua":    "data,health,hub,bughunt3",
    "Trainer.lua":     "trainer,route",
    "Probe.lua":       "trainer,guide,arrow",
    "TrainerUI.lua":   "trainer",
    "Guide.lua":       "guide,builder,editor,routes,arrow,lane05,lane10,h9lane01,h9lane02,h9lane04",
    "Arrow.lua":       "arrow,builder,guide,h9lane02",
    "RouteEditor.lua": "editor,builder,routes,guide,lane05,h9lane03",
    "Builder.lua":     "builder,routes,lane09",
    "ChatFilter.lua":  "chat,lane06",
    # From the 0.5.2 sweep: every group that caught a Core mutation (190 of 460 tests).
    "Core.lua":        "anchors,bughunt,load,queue,bughunt5,bughunt4,chat,bughunt3",
    "Quests.lua":      "quests,h9lane03",
}

STATS = { "targeted": 0, "fallback": 0 }


def _suite(dst, groups):
    env = dict(os.environ, MERCURY_PATH=dst)
    cmd = [sys.executable, os.path.join(HERE, "runner.py")] + ([groups] if groups else [])
    p = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=900)
    failing = [l.strip() for l in p.stdout.splitlines() if l.strip().startswith(("FAIL", "ERROR"))]
    return p.returncode != 0, failing


def _rm(path):
    """copytree carries the source folders' read-only bit (the OneDrive
    checkout's dirs are 0o555) and Windows will not remove a read-only
    folder, so an ignore_errors rmtree left every copy's empty folders
    behind. Clear the bit and retry the one that failed."""
    import stat

    def writable(fn, p, _):
        os.chmod(p, stat.S_IWRITE | stat.S_IREAD | stat.S_IEXEC)
        fn(p)
    try:
        shutil.rmtree(path, onerror=writable)
    except OSError:
        pass


def run(label, fname, old, new):
    tmp = tempfile.mkdtemp(prefix="salusnovus_mut_")
    dst = os.path.join(tmp, "salusnovus")
    shutil.copytree(SRC, dst)
    path = os.path.join(dst, fname)
    src = io.open(path, encoding="utf-8").read()
    if src.count(old) != 1:
        print("  ??  %s -- mutation target found %d times" % (label, src.count(old)), flush=True)
        _rm(tmp)
        return False
    io.open(path, "w", encoding="utf-8").write(src.replace(old, new, 1))
    groups = FILE_GROUPS.get(fname)
    red, failing = _suite(dst, groups)
    how = "targeted" if groups else "full"
    if not red and groups:
        # the targeted groups missed it: only the full suite may call it a survivor
        red, failing = _suite(dst, None)
        how = "fallback"
        STATS["fallback"] += 1
    else:
        STATS["targeted"] += 1
    print("  %s  %s  [%s]\n        -> %s" % ("RED " if red else "GREEN!", label, how, "; ".join(failing)[:300] or "no test noticed"), flush=True)
    _rm(tmp)
    return red


def changed_files():
    """salusnovus/*.lua touched since the last commit (staged or not)."""
    try:
        out = subprocess.run(["git", "diff", "--name-only", "HEAD", "--", "salusnovus"], cwd=ROOT,
                             capture_output=True, text=True, timeout=30).stdout
    except Exception:
        return []
    return sorted({os.path.basename(l.strip()) for l in out.splitlines() if l.strip().endswith(".lua")})


# A mutation now costs the seconds its target groups take (the full suite
# only for a survivor or an unmapped file). Four workers keep the machine
# usable; --workers N overrides.
#
#   python mutate.py                 # every mutation
#   python mutate.py --changed       # only files touched since the last commit
#   python mutate.py --files Guide.lua Arrow.lua
WORKERS = 4

if __name__ == "__main__":
    from concurrent.futures import ThreadPoolExecutor
    args = sys.argv[1:]
    workers = WORKERS
    if "--workers" in args:
        workers = int(args[args.index("--workers") + 1])
    files = None
    if "--changed" in args:
        files = changed_files()
        print("changed since HEAD: %s" % (", ".join(files) or "nothing"), flush=True)
    elif "--files" in args:
        files = [a for a in args[args.index("--files") + 1:] if not a.startswith("--")]
    todo = [m for m in MUTATIONS if files is None or m[1] in files]
    if not todo:
        print("no mutations to run", flush=True)
        sys.exit(0)
    print("%d mutation(s), %d worker(s)" % (len(todo), workers), flush=True)
    with ThreadPoolExecutor(max_workers=workers) as pool:
        results = list(pool.map(lambda m: run(*m), todo))
    print("\n%d/%d mutations caught  (targeted %d, full-suite fallback %d)" % (
        sum(results), len(results), STATS["targeted"], STATS["fallback"]), flush=True)
    sys.exit(0 if all(results) else 1)
